DROP TABLESPACE PORTAL_CORREDORES INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE PORTAL_CORREDORES DATAFILE '/u22/oradata/oradesa/datafile/portal_corredores.dbf' SIZE 80M  AUTOEXTEND ON NEXT 30M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
  
