/*
Created: 30/09/2019
Modified: 30/09/2019
Model: RE Oracle 10g
Database: Oracle 10g
*/


-- Create tables section -------------------------------------------------

-- Table INSUDB.AUTENTICACION

CREATE TABLE "INSUDB"."AUTENTICACION"(
  "COD_USUARIO" Varchar2(100 ),
  "IDENTIFICADOR" Varchar2(250 ),
  "CLAVE" Varchar2(250 ),
  "NOM_USUARIO" Varchar2(150 ),
  "ESTADO" Char(1 )
)TABLESPACE PORTAL_CORREDORES;
/

-- Table INSUDB.BROKER

CREATE TABLE "INSUDB"."BROKER"(
  "COD_BROKER" Integer,
  "COD_BROKER_VTIME" Varchar2(14 ),
  "COD_BROKER_INSUNIX" Varchar2(11 ),
  "NOM_BROKER" Varchar2(140 ),
  "FEC_ACTUALIZACION" Varchar2(100 )
)TABLESPACE PORTAL_CORREDORES;
/

-- Table INSUDB.CARGA

CREATE TABLE "INSUDB"."CARGA"(
  "ID_CARGA" Varchar2(100 ),
  "FECHA_INICIO" Varchar2(100 ),
  "FECHA_FIN" Varchar2(100 ),
  "CANT_REG" Number(10,0),
  "ESTADO" Char(1 )
)TABLESPACE PORTAL_CORREDORES;
/

-- Table INSUDB.COMERCIAL

CREATE TABLE "INSUDB"."COMERCIAL"(
  "COD_COMERCIAL" Varchar2(100 ),
  "COD_COMERCIAL_OFICINA" Varchar2(140 ),
  "NOM_EJECUTIVO_COMERCIAL" Varchar2(140 ),
  "FEC_ACTUALIZACION" Varchar2(100 )
)TABLESPACE PORTAL_CORREDORES;
/

-- Table INSUDB.COMERCIAL_BROKER

CREATE TABLE "INSUDB"."COMERCIAL_BROKER"(
  "ID_COMERCIAL" Integer,
  "ID_BROKER" Integer
)TABLESPACE PORTAL_CORREDORES;
/

-- Table INSUDB.COMPANIA

CREATE TABLE "INSUDB"."COMPANIA"(
  "COD_COMPANIA" Integer,
  "NOM_COMPANIA" Varchar2(100 ),
  "FEC_ACTUALIZACION" Varchar2(100 )
)TABLESPACE PORTAL_CORREDORES;
/

-- Table INSUDB.NETO_COASEGURO

CREATE TABLE "INSUDB"."NETO_COASEGURO"(
  "COD_ANO_MES" Varchar2(7 ),
  "ANIO" Varchar2(100 ),
  "MES" Varchar2(100 ),
  "COD_COMPANIA" Number,
  "COD_RAMO_COMERCIAL" Varchar2(10 ),
  "COD_REGION" Integer,
  "COD_BROKER" Integer,
  "COD_COMERCIAL" Integer,
  "NOM_COMPANIA" Varchar2(100 ),
  "NOM_RAMO_COMERCIAL" Varchar2(50 ),
  "NOM_REGION" Varchar2(50 ),
  "NOM_BROKER" Varchar2(140 ),
  "NOM_COMERCIAL" Varchar2(140 ),
  "MONTO_PEN" Number(11,2),
  "MONTO_USD" Number(11,2),
  "FEC_ACTUALIZACION" Date
)TABLESPACE PORTAL_CORREDORES;
/

-- Table INSUDB.PARAMETROS_EECC

CREATE TABLE "INSUDB"."PARAMETROS_EECC"(
  "TIPO_PARAMETRO" Varchar2(10 ) CONSTRAINT "SYS_C001126023" NOT NULL,
  "CODIGO" Varchar2(20 ) CONSTRAINT "SYS_C001126024" NOT NULL,
  "DESCRIPCION" Varchar2(100 ),
  "VALOR_NUMERICO" Number(11,2),
  "VALOR_CADENA" Varchar2(30 ),
  "ESTADO" Char(1 )
)TABLESPACE PORTAL_CORREDORES;
/

-- Create indexes for table INSUDB.PARAMETROS_EECC

CREATE UNIQUE INDEX "INSUDB"."PARAMETROS_PK" ON "INSUDB"."PARAMETROS_EECC" ("TIPO_PARAMETRO","CODIGO");
/

-- Table INSUDB.RAMO

CREATE TABLE "INSUDB"."RAMO"(
  "COD_RAMO_COMERCIAL" Varchar2(10 ),
  "COD_COMPANIA" Integer,
  "NOM_RAMO_COMERCIAL" Varchar2(50 ),
  "FEC_ACTUALIZACION" Varchar2(100 )
)TABLESPACE PORTAL_CORREDORES;
/

-- Table INSUDB.REGION

CREATE TABLE "INSUDB"."REGION"(
  "COD_REGION" Integer,
  "NOM_REGION" Varchar2(100 ),
  "FEC_ACTUALIZACION" Varchar2(100 )
)TABLESPACE PORTAL_CORREDORES;
/

-- Table INSUDB.COMISION
CREATE TABLE "INSUDB"."COMISION"
(
  COD_ANO_MES            VARCHAR2(7 BYTE),
  ANIO                   VARCHAR2(100 BYTE),
  MES                    VARCHAR2(100 BYTE),
  COD_COMPANIA           NUMBER,
  COD_RAMO_COMERCIAL     VARCHAR2(10 BYTE),
  COD_BROKER             INTEGER,
  NOM_COMPANIA           VARCHAR2(100 BYTE),
  NOM_RAMO_COMERCIAL     VARCHAR2(50 BYTE),
  NOM_BROKER             VARCHAR2(140 BYTE),
  COD_CLIENTE            VARCHAR2(20 BYTE),
  NOMBRE_CLIENTE         VARCHAR2(150 BYTE),
  PRIMA_SOL              NUMBER(11,2),
  PRIMA_DOL              NUMBER(11,2),
  COMISION_SOL           NUMBER(11,2),
  COMISION_USD           NUMBER(11,2),
  CANTIDAD_POLIZAS       NUMBER,
  CANTIDAD_DOC_COBRO     NUMBER,
  FEC_ACTUALIZACION      DATE,
  VENCIMIENTO_COMI_PEND  DATE,
  VENCIMIENTO_COMI_RIES  DATE,
  ESTADO_COMISION        CHAR(1 BYTE)
)TABLESPACE PORTAL_CORREDORES

/
