DROP PACKAGE INSUDB.SEGURIDADCORREDORES;

CREATE OR REPLACE PACKAGE INSUDB."SEGURIDADCORREDORES" AS

  FUNCTION ENCRIPTAR (PUSERNAME  IN  VARCHAR2,
                     PPASSWORD  IN  VARCHAR2
                     )
    RETURN VARCHAR2;
    
  PROCEDURE ADDUSUARIO (PUSERNAME  IN  VARCHAR2,
                      PPASSWORD  IN  VARCHAR2,
                     PNAME IN VARCHAR2);

  PROCEDURE CAMBIARCLAVE (PUSERNAME      IN  VARCHAR2,
                             POLDPASSWORD  IN  VARCHAR2,
                             PNEWPASSWORD  IN  VARCHAR2);

  PROCEDURE VALIDARUSUARIOP (PUSERNAME  IN  VARCHAR2,
                        PPASSWORD  IN  VARCHAR2);

  FUNCTION VALIDARUSUARIO (PUSERNAME  IN  VARCHAR2,
                       PPASSWORD  IN  VARCHAR2)
    RETURN INT;

END;
/

DROP PACKAGE BODY INSUDB.SEGURIDADCORREDORES;

CREATE OR REPLACE PACKAGE BODY INSUDB."SEGURIDADCORREDORES" AS

  FUNCTION ENCRIPTAR (PUSERNAME  IN  VARCHAR2,
                     PPASSWORD  IN  VARCHAR2
                     )
    RETURN VARCHAR2 AS
    l_salt VARCHAR2(30) := '$$POSITIVA2019%CORREDORES';
  BEGIN 
    RETURN DBMS_CRYPTO.HASH(UTL_RAW.CAST_TO_RAW(UPPER(PUSERNAME) || l_salt || UPPER(PPASSWORD)),DBMS_CRYPTO.HASH_SH1);
  END;

  PROCEDURE ADDUSUARIO (PUSERNAME  IN  VARCHAR2,
                      PPASSWORD  IN  VARCHAR2,
                     PNAME IN VARCHAR2) AS
  BEGIN

   INSERT INTO INSUDB.AUTENTICACION (COD_USUARIO,IDENTIFICADOR,CLAVE,NOM_USUARIO,ESTADO)    
  VALUES ( "INSUDB"."SEGURIDADSQ".nextval  ,UPPER(PUSERNAME),ENCRIPTAR(PUSERNAME, PPASSWORD), PNAME ,1 );

 
    COMMIT;
  END;
   
  PROCEDURE CAMBIARCLAVE (PUSERNAME      IN  VARCHAR2,
                             POLDPASSWORD  IN  VARCHAR2,
                             PNEWPASSWORD  IN  VARCHAR2) AS
    v_rowid  ROWID;
  BEGIN
    SELECT rowid
    INTO   v_rowid
    FROM   INSUDB.AUTENTICACION 
    WHERE  IDENTIFICADOR = UPPER(PUSERNAME)
    AND    CLAVE = ENCRIPTAR(PUSERNAME, POLDPASSWORD)
    FOR UPDATE;
    
    UPDATE INSUDB.AUTENTICACION 
    SET    CLAVE = ENCRIPTAR(PUSERNAME, PNEWPASSWORD)
    WHERE  rowid    = v_rowid;
    
    COMMIT;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20000, 'Invalid username/password.');
  END;

  PROCEDURE VALIDARUSUARIOP (PUSERNAME  IN  VARCHAR2,
                        PPASSWORD  IN  VARCHAR2) AS
    v_dummy  VARCHAR2(1);
  BEGIN
    SELECT '1'
    INTO   v_dummy
    FROM   INSUDB.AUTENTICACION
    WHERE  IDENTIFICADOR = UPPER(PUSERNAME)
    AND    CLAVE = ENCRIPTAR(PUSERNAME, PPASSWORD);
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20000, 'Invalid username/password.');
  END;
  
  FUNCTION VALIDARUSUARIO (PUSERNAME  IN  VARCHAR2,
                       PPASSWORD  IN  VARCHAR2) 
    RETURN INT IS
    PVALIDATION INT :=3;
  BEGIN
    VALIDARUSUARIOP(PUSERNAME, PPASSWORD);
    PVALIDATION := 1;
    RETURN PVALIDATION;
  EXCEPTION
    WHEN OTHERS THEN
    PVALIDATION := 0;
    RETURN PVALIDATION;
  END;
  
END;
/
