DROP PACKAGE WEBCORREDORES.CORREDORES_PKG_PRODUCCION;

CREATE OR REPLACE PACKAGE WEBCORREDORES."CORREDORES_PKG_PRODUCCION"
AS
     PROCEDURE CORREDORES_GET_EECC(PBUSQUEDA IN VARCHAR2, PBUSQUEDAESTADO IN VARCHAR2, OCURSOR OUT SYS_REFCURSOR)   ;
   PROCEDURE CORREDORES_GET_BELLS(OCURSOR OUT SYS_REFCURSOR);
   PROCEDURE CORREDORES_GET_RAMO(PCODIGO_COMPANIA IN VARCHAR2,PFLG IN VARCHAR2,OCURSOR OUT SYS_REFCURSOR);
   PROCEDURE CORREDORES_GET_REGION(OCURSOR OUT SYS_REFCURSOR);
   PROCEDURE CORREDORES_GET_BROKER(  OCURSOR OUT SYS_REFCURSOR);
   PROCEDURE CORREDORES_BALANCE_PRODUCCIONM(PCOMPANIA IN VARCHAR2,PRAMO IN VARCHAR2,PBROKER IN VARCHAR2,PREGION IN VARCHAR2,  PBUSQUEDAINI IN VARCHAR2,
      PBUSQUEDAFIN IN VARCHAR2, 
      PCASEBUSQUEDA IN VARCHAR2,OCURSOR OUT SYS_REFCURSOR);
      
     PROCEDURE CORREDORES_BALANCE_PRD_DETALLE(
        PCOMPANIA IN WEBCORREDORES.NETO_COASEGURO.COD_COMPANIA%TYPE,
        PRAMO IN WEBCORREDORES.NETO_COASEGURO.COD_RAMO_COMERCIAL%TYPE,
        PBROKER IN WEBCORREDORES.NETO_COASEGURO.COD_BROKER%TYPE,
        PREGION IN WEBCORREDORES.NETO_COASEGURO.COD_REGION%TYPE,
        PBUSQUEDAINI IN VARCHAR2,
      POCURSOR OUT SYS_REFCURSOR , COMOCURSOR OUT SYS_REFCURSOR , RAOCURSOR OUT SYS_REFCURSOR , REOCURSOR OUT SYS_REFCURSOR);
      
     PROCEDURE CORREDORES_AVANCE_PRD(
        PCOMPANIA IN WEBCORREDORES.NETO_COASEGURO.COD_COMPANIA%TYPE,
        PRAMO IN WEBCORREDORES.NETO_COASEGURO.COD_RAMO_COMERCIAL%TYPE,
        PBROKER IN WEBCORREDORES.NETO_COASEGURO.COD_BROKER%TYPE,
        PREGION IN WEBCORREDORES.NETO_COASEGURO.COD_REGION%TYPE,        
        PCASEBUSQUEDA IN VARCHAR2, 
        PBUSQUEDAINIF IN VARCHAR2,
        FECHAACTUALIZACION OUT VARCHAR2, --WEBCORREDORES.NETO_COASEGURO.FEC_ACTUALIZACION%TYPE, 
          ANIOPS OUT VARCHAR2,
          MESPS OUT VARCHAR2,
          MONTOANPEN OUT NUMBER,
          MONTOANUSD OUT NUMBER,
          MONTOMENPEN OUT NUMBER,
          MONTOMENUSD OUT NUMBER,
          FILTERANPEN OUT NUMBER,
          FILTERANUSD OUT NUMBER ,
          FILTERMONPEN OUT NUMBER,
          FILTERMONUSD OUT NUMBER
     );
       
END "CORREDORES_PKG_PRODUCCION";
/

DROP PACKAGE BODY WEBCORREDORES.CORREDORES_PKG_PRODUCCION;

CREATE OR REPLACE PACKAGE BODY WEBCORREDORES."CORREDORES_PKG_PRODUCCION"
AS
    
     PROCEDURE CORREDORES_GET_EECC(PBUSQUEDA IN VARCHAR2, PBUSQUEDAESTADO IN VARCHAR2, OCURSOR OUT SYS_REFCURSOR)    
      AS
      BEGIN 
            CASE
            WHEN (LENGTH (LTRIM(PBUSQUEDA))  > 0   AND (PBUSQUEDAESTADO = 'A')) THEN 
        OPEN OCURSOR FOR 
          SELECT TIPO_PARAMETRO, CODIGO , DESCRIPCION, VALOR_NUMERICO, VALOR_CADENA, ESTADO  
                    FROM WEBCORREDORES.PARAMETROS_EECC WHERE TIPO_PARAMETRO IN (
                     SELECT REGEXP_SUBSTR(PBUSQUEDA,'[^,]+', 1, LEVEL) FROM DUAL
                         CONNECT BY REGEXP_SUBSTR(PBUSQUEDA, '[^,]+', 1, LEVEL) IS NOT NULL)  
                ORDER BY TIPO_PARAMETRO;  
            WHEN (LENGTH (LTRIM(PBUSQUEDA))  > 0   AND (PBUSQUEDAESTADO <> 'A'))  THEN 
            OPEN OCURSOR FOR 
          SELECT TIPO_PARAMETRO, CODIGO , DESCRIPCION, VALOR_NUMERICO, VALOR_CADENA, ESTADO  
                    FROM WEBCORREDORES.PARAMETROS_EECC WHERE TIPO_PARAMETRO IN (
                     SELECT REGEXP_SUBSTR(PBUSQUEDA,'[^,]+', 1, LEVEL) FROM DUAL
                         CONNECT BY REGEXP_SUBSTR(PBUSQUEDA, '[^,]+', 1, LEVEL) IS NOT NULL)   AND ESTADO = PBUSQUEDAESTADO
                ORDER BY TIPO_PARAMETRO;
            WHEN (LENGTH (LTRIM(PBUSQUEDA))  = 0   AND (PBUSQUEDAESTADO <> 'A')) THEN 
            OPEN OCURSOR FOR 
          SELECT TIPO_PARAMETRO, CODIGO , DESCRIPCION, VALOR_NUMERICO, VALOR_CADENA, ESTADO  
                    FROM WEBCORREDORES.PARAMETROS_EECC WHERE ESTADO  = PBUSQUEDAESTADO
                ORDER BY TIPO_PARAMETRO;    
            ELSE   
                OPEN OCURSOR FOR 
                SELECT TIPO_PARAMETRO, CODIGO , DESCRIPCION, VALOR_NUMERICO, VALOR_CADENA, ESTADO  
                    FROM WEBCORREDORES.PARAMETROS_EECC 
                ORDER BY TIPO_PARAMETRO;  
            END CASE;
     END CORREDORES_GET_EECC;
  PROCEDURE CORREDORES_GET_BELLS ( 
      OCURSOR OUT SYS_REFCURSOR)
      AS
      BEGIN 
        OPEN OCURSOR FOR 
          SELECT COD_COMPANIA , NOM_COMPANIA FROM WEBCORREDORES.COMPANIA 
        ORDER BY COD_COMPANIA ASC ;     
    END CORREDORES_GET_BELLS;

    PROCEDURE CORREDORES_GET_RAMO( 
      PCODIGO_COMPANIA IN VARCHAR2,
      PFLG IN VARCHAR2,
        OCURSOR OUT SYS_REFCURSOR)
      AS
      BEGIN
            IF PFLG = 'T' THEN
        OPEN OCURSOR FOR  
          SELECT COD_RAMO_COMERCIAL , NOM_RAMO_COMERCIAL FROM WEBCORREDORES.RAMO  
        ORDER BY COD_RAMO_COMERCIAL ASC ; 
    ELSE 
            OPEN OCURSOR FOR  
          SELECT COD_RAMO_COMERCIAL , NOM_RAMO_COMERCIAL FROM WEBCORREDORES.RAMO 
          WHERE COD_COMPANIA = PCODIGO_COMPANIA
        ORDER BY COD_RAMO_COMERCIAL ASC ;
    END IF;    
    END CORREDORES_GET_RAMO;

    PROCEDURE CORREDORES_GET_REGION( 
      OCURSOR OUT SYS_REFCURSOR)
      AS
      BEGIN
        OPEN OCURSOR FOR 
          SELECT COD_REGION ,NOM_REGION FROM WEBCORREDORES.REGION 
        ORDER BY COD_REGION ASC ;     
    END CORREDORES_GET_REGION;

    PROCEDURE CORREDORES_GET_BROKER( 
      --PCOMERCIAL IN VARCHAR2,
      OCURSOR OUT SYS_REFCURSOR)
      AS
      BEGIN
        OPEN OCURSOR FOR 
          SELECT BR.COD_BROKER ,  BR.COD_BROKER_VTIME , BR.COD_BROKER_INSUNIX , BR.NOM_BROKER 
          FROM WEBCORREDORES.BROKER BR  
            ORDER BY COD_BROKER ASC ;     
    END CORREDORES_GET_BROKER;
    
  PROCEDURE CORREDORES_BALANCE_PRODUCCIONM( 
      PCOMPANIA IN VARCHAR2,
      PRAMO IN VARCHAR2,
      PBROKER IN VARCHAR2,
      PREGION IN VARCHAR2, 
      PBUSQUEDAINI IN VARCHAR2,
      PBUSQUEDAFIN IN VARCHAR2,
      PCASEBUSQUEDA IN VARCHAR2,
      OCURSOR OUT SYS_REFCURSOR)
      
      AS
      BEGIN 
            CASE 
                WHEN PCASEBUSQUEDA='T'  THEN 
                    OPEN OCURSOR FOR 
                        SELECT COD_ANO_MES , ANIO, MES , SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , FEC_ACTUALIZACION
                            FROM (
                            SELECT COD_ANO_MES, ANIO, MES, SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , 
                            to_char(FEC_ACTUALIZACION , 'DD/MM/YYYY') AS FEC_ACTUALIZACION
                        FROM WEBCORREDORES.NETO_COASEGURO
                        WHERE COD_ANO_MES BETWEEN PBUSQUEDAINI AND  PBUSQUEDAFIN 
                        GROUP BY COD_ANO_MES, ANIO, MES,    FEC_ACTUALIZACION)
                      GROUP BY COD_ANO_MES, ANIO, MES ,FEC_ACTUALIZACION
                      ORDER BY COD_ANO_MES DESC ;
                WHEN PCASEBUSQUEDA='TC'  THEN 
                    OPEN OCURSOR FOR 
                        SELECT COD_ANO_MES , ANIO, MES , SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , FEC_ACTUALIZACION
                            FROM (
                            SELECT COD_ANO_MES, ANIO, MES, SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , 
                            to_char(FEC_ACTUALIZACION , 'DD/MM/YYYY') AS FEC_ACTUALIZACION
                        FROM WEBCORREDORES.NETO_COASEGURO
                        WHERE COD_COMPANIA = PCOMPANIA AND  
                                COD_ANO_MES BETWEEN PBUSQUEDAINI AND  PBUSQUEDAFIN 
                        GROUP BY COD_ANO_MES, ANIO, MES,    FEC_ACTUALIZACION)
                      GROUP BY COD_ANO_MES, ANIO, MES ,FEC_ACTUALIZACION
                      ORDER BY COD_ANO_MES DESC ;
                       
                WHEN PCASEBUSQUEDA='TCR'  THEN 
                    OPEN OCURSOR FOR 
                        SELECT COD_ANO_MES , ANIO, MES , SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , FEC_ACTUALIZACION
                            FROM (
                            SELECT COD_ANO_MES, ANIO, MES, SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , 
                            to_char(FEC_ACTUALIZACION , 'DD/MM/YYYY') AS FEC_ACTUALIZACION
                        FROM WEBCORREDORES.NETO_COASEGURO
                        WHERE COD_COMPANIA = PCOMPANIA AND 
                                COD_RAMO_COMERCIAL=PRAMO AND 
                                COD_ANO_MES BETWEEN PBUSQUEDAINI AND  PBUSQUEDAFIN 
                        GROUP BY COD_ANO_MES, ANIO, MES,   FEC_ACTUALIZACION)
                      GROUP BY COD_ANO_MES, ANIO, MES ,FEC_ACTUALIZACION
                      ORDER BY COD_ANO_MES DESC ;
                      
                WHEN PCASEBUSQUEDA='TCG'  THEN 
                    OPEN OCURSOR FOR 
                        SELECT COD_ANO_MES , ANIO, MES , SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , FEC_ACTUALIZACION
                            FROM (
                            SELECT COD_ANO_MES, ANIO, MES, SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , 
                            to_char(FEC_ACTUALIZACION , 'DD/MM/YYYY') AS FEC_ACTUALIZACION
                        FROM WEBCORREDORES.NETO_COASEGURO
                        WHERE COD_COMPANIA = PCOMPANIA AND 
                                COD_REGION = PREGION  AND 
                                COD_ANO_MES BETWEEN PBUSQUEDAINI AND  PBUSQUEDAFIN 
                        GROUP BY COD_ANO_MES, ANIO, MES,   FEC_ACTUALIZACION)
                      GROUP BY COD_ANO_MES, ANIO, MES ,FEC_ACTUALIZACION
                      ORDER BY COD_ANO_MES DESC ;
                      
                WHEN PCASEBUSQUEDA='TR'  THEN 
                    OPEN OCURSOR FOR 
                        SELECT COD_ANO_MES , ANIO, MES , SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , FEC_ACTUALIZACION
                            FROM (
                            SELECT COD_ANO_MES, ANIO, MES, SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , 
                            to_char(FEC_ACTUALIZACION , 'DD/MM/YYYY') AS FEC_ACTUALIZACION
                        FROM WEBCORREDORES.NETO_COASEGURO
                        WHERE  
                                COD_RAMO_COMERCIAL=PRAMO AND 
                                COD_ANO_MES BETWEEN PBUSQUEDAINI AND  PBUSQUEDAFIN 
                        GROUP BY COD_ANO_MES, ANIO, MES,    FEC_ACTUALIZACION)
                      GROUP BY COD_ANO_MES, ANIO, MES ,FEC_ACTUALIZACION
                      ORDER BY COD_ANO_MES DESC ; 
                WHEN PCASEBUSQUEDA='TRG'  THEN 
                    OPEN OCURSOR FOR 
                        SELECT COD_ANO_MES , ANIO, MES , SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , FEC_ACTUALIZACION
                            FROM (
                            SELECT COD_ANO_MES, ANIO, MES, SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , 
                            to_char(FEC_ACTUALIZACION , 'DD/MM/YYYY') AS FEC_ACTUALIZACION
                        FROM WEBCORREDORES.NETO_COASEGURO
                        WHERE  COD_REGION = PREGION AND  
                                COD_RAMO_COMERCIAL=PRAMO AND 
                                COD_ANO_MES BETWEEN PBUSQUEDAINI AND  PBUSQUEDAFIN 
                        GROUP BY COD_ANO_MES, ANIO, MES,   FEC_ACTUALIZACION)
                      GROUP BY COD_ANO_MES, ANIO, MES ,FEC_ACTUALIZACION
                      ORDER BY COD_ANO_MES DESC ; 
                      
                 WHEN PCASEBUSQUEDA='TRGB'  THEN 
                    OPEN OCURSOR FOR 
                        SELECT COD_ANO_MES , ANIO, MES , SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , FEC_ACTUALIZACION
                            FROM (
                            SELECT COD_ANO_MES, ANIO, MES, SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , 
                            to_char(FEC_ACTUALIZACION , 'DD/MM/YYYY') AS FEC_ACTUALIZACION
                        FROM WEBCORREDORES.NETO_COASEGURO
                        WHERE   COD_BROKER = PBROKER AND  
                                COD_REGION = PREGION AND  
                                COD_RAMO_COMERCIAL=PRAMO AND 
                                COD_ANO_MES BETWEEN PBUSQUEDAINI AND  PBUSQUEDAFIN 
                        GROUP BY COD_ANO_MES, ANIO, MES,   FEC_ACTUALIZACION)
                      GROUP BY COD_ANO_MES, ANIO, MES ,FEC_ACTUALIZACION
                      ORDER BY COD_ANO_MES DESC ;      
                WHEN PCASEBUSQUEDA='TCRG'  THEN 
                    OPEN OCURSOR FOR 
                        SELECT COD_ANO_MES , ANIO, MES , SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , FEC_ACTUALIZACION
                            FROM (
                            SELECT COD_ANO_MES, ANIO, MES, SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , 
                            to_char(FEC_ACTUALIZACION , 'DD/MM/YYYY') AS FEC_ACTUALIZACION
                        FROM WEBCORREDORES.NETO_COASEGURO
                        WHERE  COD_COMPANIA = PCOMPANIA AND 
                                COD_RAMO_COMERCIAL=PRAMO AND 
                                COD_REGION = PREGION AND  
                                COD_ANO_MES BETWEEN PBUSQUEDAINI AND  PBUSQUEDAFIN 
                        GROUP BY COD_ANO_MES, ANIO, MES,   FEC_ACTUALIZACION)
                      GROUP BY COD_ANO_MES, ANIO, MES ,FEC_ACTUALIZACION
                      ORDER BY COD_ANO_MES DESC ;
                      
                WHEN PCASEBUSQUEDA='TG'  THEN  -- SOLO POR REGION
                    OPEN OCURSOR FOR 
                        SELECT COD_ANO_MES , ANIO, MES , SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , FEC_ACTUALIZACION
                            FROM (
                            SELECT COD_ANO_MES, ANIO, MES, SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , 
                            to_char(FEC_ACTUALIZACION , 'DD/MM/YYYY') AS FEC_ACTUALIZACION
                        FROM WEBCORREDORES.NETO_COASEGURO
                        WHERE  COD_REGION = PREGION AND  
                                COD_ANO_MES BETWEEN PBUSQUEDAINI AND  PBUSQUEDAFIN 
                        GROUP BY COD_ANO_MES, ANIO, MES,   FEC_ACTUALIZACION)
                      GROUP BY COD_ANO_MES, ANIO, MES ,FEC_ACTUALIZACION
                      ORDER BY COD_ANO_MES DESC ;
                WHEN PCASEBUSQUEDA='TB'  THEN  -- SOLO POR BROKER
                    OPEN OCURSOR FOR 
                        SELECT COD_ANO_MES , ANIO, MES , SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , FEC_ACTUALIZACION
                            FROM (
                            SELECT COD_ANO_MES, ANIO, MES, SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , 
                            to_char(FEC_ACTUALIZACION , 'DD/MM/YYYY') AS FEC_ACTUALIZACION
                        FROM WEBCORREDORES.NETO_COASEGURO
                        WHERE   COD_BROKER = PBROKER AND  
                                COD_ANO_MES BETWEEN PBUSQUEDAINI AND  PBUSQUEDAFIN 
                        GROUP BY COD_ANO_MES, ANIO, MES,  FEC_ACTUALIZACION)
                      GROUP BY COD_ANO_MES, ANIO, MES ,FEC_ACTUALIZACION
                      ORDER BY COD_ANO_MES DESC ;
                        
                WHEN PCASEBUSQUEDA='TGB'  THEN  -- SOLO POR BROKER AND REGION
                    OPEN OCURSOR FOR 
                        SELECT COD_ANO_MES , ANIO, MES , SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , FEC_ACTUALIZACION
                            FROM (
                            SELECT COD_ANO_MES, ANIO, MES, SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , 
                            to_char(FEC_ACTUALIZACION , 'DD/MM/YYYY') AS FEC_ACTUALIZACION
                        FROM WEBCORREDORES.NETO_COASEGURO
                          WHERE   COD_REGION = PREGION AND 
                                COD_BROKER = PBROKER AND  
                                COD_ANO_MES BETWEEN PBUSQUEDAINI AND  PBUSQUEDAFIN 
                        GROUP BY COD_ANO_MES, ANIO, MES,   FEC_ACTUALIZACION)
                      GROUP BY COD_ANO_MES, ANIO, MES ,FEC_ACTUALIZACION
                      ORDER BY COD_ANO_MES DESC ; 
                        
                WHEN PCASEBUSQUEDA='TCRGB'  THEN 
                    OPEN OCURSOR FOR 
                        SELECT COD_ANO_MES , ANIO, MES , SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , FEC_ACTUALIZACION
                            FROM (
                            SELECT COD_ANO_MES, ANIO, MES, SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD  , 
                            to_char(FEC_ACTUALIZACION , 'DD/MM/YYYY') AS FEC_ACTUALIZACION
                        FROM WEBCORREDORES.NETO_COASEGURO
                         WHERE   COD_COMPANIA = PCOMPANIA AND 
                                COD_RAMO_COMERCIAL=PRAMO AND 
                                COD_REGION = PREGION AND  
                                COD_BROKER = PBROKER AND
                                COD_ANO_MES BETWEEN PBUSQUEDAINI AND  PBUSQUEDAFIN 
                        GROUP BY COD_ANO_MES, ANIO, MES,  FEC_ACTUALIZACION)
                      GROUP BY COD_ANO_MES, ANIO, MES ,FEC_ACTUALIZACION
                      ORDER BY COD_ANO_MES DESC ; 
                     
            END CASE;
    END CORREDORES_BALANCE_PRODUCCIONM;
    
    PROCEDURE CORREDORES_BALANCE_PRD_DETALLE( 
      PCOMPANIA IN WEBCORREDORES.NETO_COASEGURO.COD_COMPANIA%TYPE,
      PRAMO IN WEBCORREDORES.NETO_COASEGURO.COD_RAMO_COMERCIAL%TYPE,
      PBROKER IN WEBCORREDORES.NETO_COASEGURO.COD_BROKER%TYPE,
      PREGION IN WEBCORREDORES.NETO_COASEGURO.COD_REGION%TYPE,
      PBUSQUEDAINI IN VARCHAR2,  
      POCURSOR OUT SYS_REFCURSOR , 
      COMOCURSOR OUT SYS_REFCURSOR , 
      RAOCURSOR OUT SYS_REFCURSOR , 
      REOCURSOR OUT SYS_REFCURSOR)
      
      AS
      VFECHA VARCHAR2(100);
      BEGIN  
        CASE 
                WHEN PBUSQUEDAINI='T'  THEN 
                    OPEN POCURSOR FOR 
                        SELECT 
                          SUBSTR(COD_ANO_MES,0,4) ANIO,  SUBSTR(COD_ANO_MES,5,2) AS MES_CODIGO, SUM(MONTO_PEN) MONTO_PEN ,
                          SUM(MONTO_USD)MONTO_USD ,MES,  FEC_ACTUALIZACION
                          FROM WEBCORREDORES.NETO_COASEGURO                
                             GROUP BY COD_ANO_MES ,    MES ,FEC_ACTUALIZACION--, to_char(FEC_ACTUALIZACION , 'DD/MM/YYYY') 
                             ORDER BY SUBSTR(COD_ANO_MES,5,2) DESC , SUBSTR(COD_ANO_MES,0,4) DESC;
                             
                WHEN PBUSQUEDAINI='TC'  THEN 
                    OPEN POCURSOR FOR 
                        SELECT
                            SUBSTR(COD_ANO_MES,0,4) ANIO,  SUBSTR(COD_ANO_MES,5,2) AS MES_CODIGO, SUM(MONTO_PEN) MONTO_PEN ,
                          SUM(MONTO_USD)MONTO_USD  ,MES,FEC_ACTUALIZACION
                            FROM WEBCORREDORES.NETO_COASEGURO  
                             WHERE   COD_COMPANIA = PCOMPANIA                
                             GROUP BY COD_ANO_MES ,    MES , FEC_ACTUALIZACION
                             ORDER  BY SUBSTR(COD_ANO_MES,5,2) DESC , SUBSTR(COD_ANO_MES,0,4) DESC;
                WHEN PBUSQUEDAINI='TCR'  THEN 
                    OPEN POCURSOR FOR 
                        SELECT
                            SUBSTR(COD_ANO_MES,0,4) ANIO,  SUBSTR(COD_ANO_MES,5,2) AS MES_CODIGO, SUM(MONTO_PEN) MONTO_PEN ,
                          SUM(MONTO_USD)MONTO_USD ,MES,FEC_ACTUALIZACION
                            FROM WEBCORREDORES.NETO_COASEGURO   
                        WHERE   COD_COMPANIA = PCOMPANIA AND 
                                COD_RAMO_COMERCIAL=PRAMO   
                       GROUP BY COD_ANO_MES  ,MES , FEC_ACTUALIZACION
                       ORDER  BY SUBSTR(COD_ANO_MES,5,2) DESC , SUBSTR(COD_ANO_MES,0,4) DESC;
                WHEN PBUSQUEDAINI='TR'  THEN 
                    OPEN POCURSOR FOR 
                        SELECT
                            SUBSTR(COD_ANO_MES,0,4) ANIO,  SUBSTR(COD_ANO_MES,5,2) AS MES_CODIGO, SUM(MONTO_PEN) MONTO_PEN ,
                          SUM(MONTO_USD)MONTO_USD ,MES,FEC_ACTUALIZACION
                            FROM WEBCORREDORES.NETO_COASEGURO   
                        WHERE   COD_RAMO_COMERCIAL=PRAMO   
                       GROUP BY COD_ANO_MES  ,MES , FEC_ACTUALIZACION
                       ORDER BY SUBSTR(COD_ANO_MES,5,2) DESC , SUBSTR(COD_ANO_MES,0,4) DESC; 
                WHEN PBUSQUEDAINI='TRG'  THEN 
                    OPEN POCURSOR FOR 
                        SELECT
                            SUBSTR(COD_ANO_MES,0,4) ANIO,  SUBSTR(COD_ANO_MES,5,2) AS MES_CODIGO, SUM(MONTO_PEN) MONTO_PEN ,
                          SUM(MONTO_USD)MONTO_USD  ,MES,FEC_ACTUALIZACION
                            FROM WEBCORREDORES.NETO_COASEGURO   
                        WHERE  COD_RAMO_COMERCIAL=PRAMO  AND  COD_REGION = PREGION 
                        GROUP BY COD_ANO_MES ,   MES , FEC_ACTUALIZACION
                        ORDER  BY SUBSTR(COD_ANO_MES,5,2) DESC , SUBSTR(COD_ANO_MES,0,4) DESC;
                        
                 WHEN PBUSQUEDAINI='TCRG'  THEN 
                    OPEN POCURSOR FOR 
                        SELECT
                            SUBSTR(COD_ANO_MES,0,4) ANIO,  SUBSTR(COD_ANO_MES,5,2) AS MES_CODIGO,SUM(MONTO_PEN) MONTO_PEN ,
                          SUM(MONTO_USD)MONTO_USD  ,MES,FEC_ACTUALIZACION
                            FROM WEBCORREDORES.NETO_COASEGURO   
                        WHERE   COD_COMPANIA = PCOMPANIA AND 
                                COD_RAMO_COMERCIAL=PRAMO AND 
                                COD_REGION = PREGION    
                       GROUP BY COD_ANO_MES ,   MES , FEC_ACTUALIZACION
                       ORDER  BY SUBSTR(COD_ANO_MES,5,2) DESC , SUBSTR(COD_ANO_MES,0,4) DESC;
                 WHEN PBUSQUEDAINI='TRGB'  THEN 
                    OPEN POCURSOR FOR 
                        SELECT
                            SUBSTR(COD_ANO_MES,0,4) ANIO,  SUBSTR(COD_ANO_MES,5,2) AS MES_CODIGO, SUM(MONTO_PEN) MONTO_PEN ,
                          SUM(MONTO_USD)MONTO_USD ,MES,FEC_ACTUALIZACION
                            FROM WEBCORREDORES.NETO_COASEGURO   
                        WHERE   COD_BROKER = PBROKER AND
                                COD_RAMO_COMERCIAL=PRAMO AND 
                                COD_REGION = PREGION   AND COD_BROKER = PBROKER
                        GROUP BY COD_ANO_MES ,  MES , FEC_ACTUALIZACION
                        ORDER  BY SUBSTR(COD_ANO_MES,5,2) DESC , SUBSTR(COD_ANO_MES,0,4) DESC;
                 WHEN PBUSQUEDAINI='TG'  THEN 
                    OPEN POCURSOR FOR 
                        SELECT
                            SUBSTR(COD_ANO_MES,0,4) ANIO,  SUBSTR(COD_ANO_MES,5,2) AS MES_CODIGO, SUM(MONTO_PEN) MONTO_PEN ,
                          SUM(MONTO_USD)MONTO_USD ,MES,FEC_ACTUALIZACION
                            FROM WEBCORREDORES.NETO_COASEGURO   
                        WHERE   
                                COD_REGION = PREGION   
                        GROUP BY COD_ANO_MES ,    MES , FEC_ACTUALIZACION
                        ORDER  BY SUBSTR(COD_ANO_MES,5,2) DESC , SUBSTR(COD_ANO_MES,0,4) DESC;           
                 WHEN PBUSQUEDAINI='TB'  THEN 
                    OPEN POCURSOR FOR 
                        SELECT
                            SUBSTR(COD_ANO_MES,0,4) ANIO,  SUBSTR(COD_ANO_MES,5,2) AS MES_CODIGO, SUM(MONTO_PEN) MONTO_PEN ,
                          SUM(MONTO_USD)MONTO_USD ,MES,FEC_ACTUALIZACION
                            FROM WEBCORREDORES.NETO_COASEGURO   
                        WHERE   COD_BROKER = PBROKER
                        GROUP BY COD_ANO_MES ,  MES , FEC_ACTUALIZACION
                        ORDER  BY SUBSTR(COD_ANO_MES,5,2) DESC , SUBSTR(COD_ANO_MES,0,4) DESC; 
                        
                WHEN PBUSQUEDAINI='TCG'  THEN 
                    OPEN POCURSOR FOR 
                        SELECT
                            SUBSTR(COD_ANO_MES,0,4) ANIO,  SUBSTR(COD_ANO_MES,5,2) AS MES_CODIGO, SUM(MONTO_PEN) MONTO_PEN ,
                          SUM(MONTO_USD)MONTO_USD  ,MES,FEC_ACTUALIZACION
                            FROM WEBCORREDORES.NETO_COASEGURO   
                        WHERE   COD_COMPANIA = PCOMPANIA  AND  COD_REGION = PREGION 
                        GROUP BY COD_ANO_MES ,   MES , FEC_ACTUALIZACION
                        ORDER  BY SUBSTR(COD_ANO_MES,5,2) DESC , SUBSTR(COD_ANO_MES,0,4) DESC;         
                        
                WHEN PBUSQUEDAINI='TGB'  THEN 
                    OPEN POCURSOR FOR 
                        SELECT
                            SUBSTR(COD_ANO_MES,0,4) ANIO,  SUBSTR(COD_ANO_MES,5,2) AS MES_CODIGO, SUM(MONTO_PEN) MONTO_PEN ,
                          SUM(MONTO_USD)MONTO_USD  ,MES,FEC_ACTUALIZACION
                            FROM WEBCORREDORES.NETO_COASEGURO   
                        WHERE   COD_BROKER = PBROKER AND  COD_REGION = PREGION 
                        GROUP BY COD_ANO_MES ,   MES , FEC_ACTUALIZACION
                        ORDER  BY SUBSTR(COD_ANO_MES,5,2) DESC , SUBSTR(COD_ANO_MES,0,4) DESC;        
              
                WHEN PBUSQUEDAINI='TCRGB'  THEN 
                    OPEN POCURSOR FOR 
                        SELECT
                            SUBSTR(COD_ANO_MES,0,4) ANIO,  SUBSTR(COD_ANO_MES,5,2) AS MES_CODIGO, SUM(MONTO_PEN) MONTO_PEN ,
                          SUM(MONTO_USD)MONTO_USD ,MES,FEC_ACTUALIZACION
                            FROM WEBCORREDORES.NETO_COASEGURO   
                        WHERE   COD_COMPANIA = PCOMPANIA AND 
                                COD_RAMO_COMERCIAL=PRAMO AND 
                                COD_REGION = PREGION   AND COD_BROKER = PBROKER
                        GROUP BY COD_ANO_MES ,  MES , FEC_ACTUALIZACION
                        ORDER  BY SUBSTR(COD_ANO_MES,5,2) DESC , SUBSTR(COD_ANO_MES,0,4) DESC;
               
            END CASE;             
                     
         IF PCOMPANIA <>  0 THEN
            OPEN COMOCURSOR FOR 
                SELECT COD_COMPANIA, NOM_COMPANIA, SUM(MONTO_PEN) MONTO_PEN ,SUM(MONTO_USD)  MONTO_USD FROM (
                SELECT 
                    COD_COMPANIA, NOM_COMPANIA,    SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD ,SUBSTR(COD_ANO_MES,0,4)  COD_ANO_MES
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE COD_COMPANIA= PCOMPANIA
                GROUP BY COD_COMPANIA,  NOM_COMPANIA,   MONTO_PEN , MONTO_USD ,COD_ANO_MES
                ) GROUP BY COD_COMPANIA, NOM_COMPANIA , COD_ANO_MES ORDER BY COD_COMPANIA ASC, COD_ANO_MES DESC;
         ELSE 
             OPEN COMOCURSOR FOR 
                SELECT COD_COMPANIA, NOM_COMPANIA, SUM(MONTO_PEN) MONTO_PEN ,SUM(MONTO_USD)  MONTO_USD FROM (
                SELECT 
                    COD_COMPANIA, NOM_COMPANIA,    SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD ,SUBSTR(COD_ANO_MES,0,4)  COD_ANO_MES
                    FROM WEBCORREDORES.NETO_COASEGURO 
                GROUP BY COD_COMPANIA,  NOM_COMPANIA,   MONTO_PEN , MONTO_USD ,COD_ANO_MES
                ) GROUP BY COD_COMPANIA, NOM_COMPANIA , COD_ANO_MES ORDER BY COD_COMPANIA asc, COD_ANO_MES DESC;
         END IF; 
         
         
        IF PRAMO <>  'T' THEN
            OPEN RAOCURSOR FOR 
                SELECT COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL, SUM(MONTO_PEN) MONTO_PEN ,SUM(MONTO_USD)  MONTO_USD FROM (
                SELECT 
                    COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL,    SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD ,SUBSTR(COD_ANO_MES,0,4)  COD_ANO_MES
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE COD_RAMO_COMERCIAL= PRAMO
                GROUP BY COD_RAMO_COMERCIAL,  NOM_RAMO_COMERCIAL,   MONTO_PEN , MONTO_USD ,COD_ANO_MES
                ) GROUP BY COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL , COD_ANO_MES ORDER BY COD_RAMO_COMERCIAL asc, COD_ANO_MES DESC;
         ELSE 
             OPEN RAOCURSOR FOR 
                SELECT COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL, SUM(MONTO_PEN) MONTO_PEN ,SUM(MONTO_USD)  MONTO_USD FROM (
                SELECT 
                    COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL,    SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD ,SUBSTR(COD_ANO_MES,0,4)  COD_ANO_MES
                    FROM WEBCORREDORES.NETO_COASEGURO  
                GROUP BY COD_RAMO_COMERCIAL,  NOM_RAMO_COMERCIAL,   MONTO_PEN , MONTO_USD ,COD_ANO_MES
                ) GROUP BY COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL , COD_ANO_MES ORDER BY COD_RAMO_COMERCIAL asc, COD_ANO_MES DESC;
         END IF; 
         
         
         IF PREGION <>  0 THEN
            OPEN REOCURSOR FOR 
                SELECT COD_REGION, NOM_REGION, SUM(MONTO_PEN) MONTO_PEN ,SUM(MONTO_USD)  MONTO_USD FROM (
                SELECT 
                    COD_REGION, NOM_REGION,    SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD ,SUBSTR(COD_ANO_MES,0,4)  COD_ANO_MES
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE COD_REGION= PREGION
                GROUP BY COD_REGION,  NOM_REGION,   MONTO_PEN , MONTO_USD ,COD_ANO_MES
                ) GROUP BY COD_REGION, NOM_REGION , COD_ANO_MES ORDER BY COD_REGION asc, COD_ANO_MES DESC;
         ELSE 
             OPEN REOCURSOR FOR 
                SELECT COD_REGION, NOM_REGION, SUM(MONTO_PEN) MONTO_PEN ,SUM(MONTO_USD)  MONTO_USD  FROM (
                SELECT 
                    COD_REGION, NOM_REGION,    SUM(MONTO_PEN) AS MONTO_PEN , SUM(MONTO_USD) AS MONTO_USD ,SUBSTR(COD_ANO_MES,0,4)  COD_ANO_MES
                    FROM WEBCORREDORES.NETO_COASEGURO  
                GROUP BY COD_REGION,  NOM_REGION,   MONTO_PEN , MONTO_USD ,COD_ANO_MES
                ) GROUP BY COD_REGION, NOM_REGION , COD_ANO_MES ORDER BY COD_REGION asc, COD_ANO_MES DESC;
         END IF;       
         
         
    END CORREDORES_BALANCE_PRD_DETALLE;

    PROCEDURE CORREDORES_AVANCE_PRD(
    PCOMPANIA IN WEBCORREDORES.NETO_COASEGURO.COD_COMPANIA%TYPE,
      PRAMO IN WEBCORREDORES.NETO_COASEGURO.COD_RAMO_COMERCIAL%TYPE,
      PBROKER IN WEBCORREDORES.NETO_COASEGURO.COD_BROKER%TYPE,
      PREGION IN WEBCORREDORES.NETO_COASEGURO.COD_REGION%TYPE,
      PCASEBUSQUEDA IN VARCHAR2, 
      PBUSQUEDAINIF IN VARCHAR2,
      
      FECHAACTUALIZACION OUT VARCHAR2 , --WEBCORREDORES.NETO_COASEGURO.FEC_ACTUALIZACION%TYPE, 
      ANIOPS OUT VARCHAR2,
      MESPS OUT VARCHAR2,
      MONTOANPEN OUT NUMBER,
      MONTOANUSD OUT NUMBER,
      MONTOMENPEN OUT NUMBER,
      MONTOMENUSD OUT NUMBER,
      FILTERANPEN OUT NUMBER,
      FILTERANUSD OUT NUMBER ,
      FILTERMONPEN OUT NUMBER,
      FILTERMONUSD OUT NUMBER
      )
      AS 
      BEGIN   
        BEGIN
            SELECT to_char(FEC_ACTUALIZACION , 'DD/MM/YYYY') AS FECHA, SUBSTR(COD_ANO_MES,0,4) ANIO , SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN
                   INTO     FECHAACTUALIZACION , ANIOPS  ,   MONTOANUSD,  MONTOANPEN
                   FROM WEBCORREDORES.NETO_COASEGURO 
                  WHERE  SUBSTR(COD_ANO_MES,0,4) =  SUBSTR(PBUSQUEDAINIF,0,4)  
                  GROUP BY SUBSTR(COD_ANO_MES,0,4) , FEC_ACTUALIZACION; 
            EXCEPTION
                  WHEN no_data_found
                  THEN
                    FECHAACTUALIZACION := ''; ANIOPS := ''; MONTOANUSD := 0; MONTOANPEN := 0;           
            END; 
            BEGIN      
            SELECT        
                    SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN  , MES
                   INTO   MONTOMENUSD            ,MONTOMENPEN     , MESPS               
                    FROM WEBCORREDORES.NETO_COASEGURO 
                   WHERE COD_ANO_MES = PBUSQUEDAINIF
                   GROUP BY SUBSTR(COD_ANO_MES,5,2) , MES;
            EXCEPTION
                  WHEN no_data_found
                  THEN   
                    MONTOMENUSD:=0; MONTOMENPEN:=0; MESPS:=' ';          
            END;      
            /*\
                    FILTRADO ANUAL Y MENSUAL
            */
            BEGIN
            CASE
            WHEN PCASEBUSQUEDA='T'  THEN  
                SELECT SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN INTO  FILTERANUSD ,FILTERANPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  SUBSTR(COD_ANO_MES,0,4)  = SUBSTR(PBUSQUEDAINIF,0,4)
                    GROUP BY SUBSTR(COD_ANO_MES,0,4);                    
                SELECT        
                    SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN 
                    INTO  FILTERMONUSD  ,FILTERMONPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  COD_ANO_MES = PBUSQUEDAINIF 
                    GROUP BY COD_ANO_MES;              
            WHEN PCASEBUSQUEDA='TC'  THEN  
                SELECT SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN INTO  FILTERANUSD ,FILTERANPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  SUBSTR(COD_ANO_MES,0,4)  = SUBSTR(PBUSQUEDAINIF,0,4) AND COD_COMPANIA = PCOMPANIA  
                    GROUP BY SUBSTR(COD_ANO_MES,0,4);                    
                SELECT        
                    SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN 
                    INTO  FILTERMONUSD  ,FILTERMONPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  COD_ANO_MES = PBUSQUEDAINIF AND  COD_COMPANIA = PCOMPANIA 
                    GROUP BY COD_ANO_MES;
            WHEN PCASEBUSQUEDA='TCR'  THEN  
                SELECT SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN INTO  FILTERANUSD ,FILTERANPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  SUBSTR(COD_ANO_MES,0,4)  = SUBSTR(PBUSQUEDAINIF,0,4) AND 
                    COD_COMPANIA = PCOMPANIA AND COD_RAMO_COMERCIAL=PRAMO 
                    GROUP BY SUBSTR(COD_ANO_MES,0,4);                    
                SELECT        
                    SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN 
                    INTO  FILTERMONUSD  ,FILTERMONPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  COD_ANO_MES = PBUSQUEDAINIF AND   COD_COMPANIA = PCOMPANIA AND COD_RAMO_COMERCIAL=PRAMO 
                    GROUP BY COD_ANO_MES;  
            WHEN PCASEBUSQUEDA='TR'  THEN  
                SELECT SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN INTO  FILTERANUSD ,FILTERANPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  SUBSTR(COD_ANO_MES,0,4)  = SUBSTR(PBUSQUEDAINIF,0,4) AND   COD_RAMO_COMERCIAL=PRAMO 
                    GROUP BY SUBSTR(COD_ANO_MES,0,4);                    
                SELECT        
                    SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN 
                    INTO  FILTERMONUSD  ,FILTERMONPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  COD_ANO_MES = PBUSQUEDAINIF AND   COD_RAMO_COMERCIAL=PRAMO 
                    GROUP BY COD_ANO_MES;  
                    
            WHEN PCASEBUSQUEDA='TRG'  THEN  
                SELECT SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN INTO  FILTERANUSD ,FILTERANPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  SUBSTR(COD_ANO_MES,0,4)  = SUBSTR(PBUSQUEDAINIF,0,4) AND COD_RAMO_COMERCIAL=PRAMO AND  COD_REGION = PREGION   
                    GROUP BY SUBSTR(COD_ANO_MES,0,4);                    
                SELECT        
                    SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN 
                    INTO  FILTERMONUSD  ,FILTERMONPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  COD_ANO_MES = PBUSQUEDAINIF AND  COD_RAMO_COMERCIAL=PRAMO AND  COD_REGION = PREGION   
                    GROUP BY COD_ANO_MES;   
             WHEN PCASEBUSQUEDA='TCG'  THEN  
                SELECT SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN INTO  FILTERANUSD ,FILTERANPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  SUBSTR(COD_ANO_MES,0,4)  = SUBSTR(PBUSQUEDAINIF,0,4) AND COD_COMPANIA = PCOMPANIA  AND  COD_REGION = PREGION   
                    GROUP BY SUBSTR(COD_ANO_MES,0,4);                    
                SELECT        
                    SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN 
                    INTO  FILTERMONUSD  ,FILTERMONPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  COD_ANO_MES = PBUSQUEDAINIF AND   COD_COMPANIA = PCOMPANIA  AND  COD_REGION = PREGION   
                    GROUP BY COD_ANO_MES;          
            WHEN PCASEBUSQUEDA='TRGB'  THEN  
                SELECT SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN INTO  FILTERANUSD ,FILTERANPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  SUBSTR(COD_ANO_MES,0,4)  = SUBSTR(PBUSQUEDAINIF,0,4) AND COD_RAMO_COMERCIAL=PRAMO AND  COD_REGION = PREGION   AND COD_BROKER = PBROKER
                    GROUP BY SUBSTR(COD_ANO_MES,0,4);                    
                SELECT        
                    SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN 
                    INTO  FILTERMONUSD  ,FILTERMONPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  COD_ANO_MES = PBUSQUEDAINIF AND  COD_RAMO_COMERCIAL=PRAMO AND  COD_REGION = PREGION   AND COD_BROKER = PBROKER
                    GROUP BY COD_ANO_MES;  
                    
             WHEN PCASEBUSQUEDA='TCRG'  THEN  
                SELECT SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN INTO  FILTERANUSD ,FILTERANPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  SUBSTR(COD_ANO_MES,0,4)  = SUBSTR(PBUSQUEDAINIF,0,4) AND 
                    COD_COMPANIA = PCOMPANIA AND COD_RAMO_COMERCIAL=PRAMO AND  COD_REGION = PREGION    
                    GROUP BY SUBSTR(COD_ANO_MES,0,4);                    
                SELECT        
                    SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN 
                    INTO  FILTERMONUSD  ,FILTERMONPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  COD_ANO_MES = PBUSQUEDAINIF AND  COD_COMPANIA = PCOMPANIA AND COD_RAMO_COMERCIAL=PRAMO AND  COD_REGION = PREGION   
                    GROUP BY COD_ANO_MES;  
                    
             WHEN PCASEBUSQUEDA='TG'  THEN  
                SELECT SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN INTO  FILTERANUSD ,FILTERANPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  SUBSTR(COD_ANO_MES,0,4)  = SUBSTR(PBUSQUEDAINIF,0,4) AND   COD_REGION = PREGION    
                    GROUP BY SUBSTR(COD_ANO_MES,0,4);                    
                SELECT        
                    SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN 
                    INTO  FILTERMONUSD  ,FILTERMONPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  COD_ANO_MES = PBUSQUEDAINIF AND   COD_REGION = PREGION    
                    GROUP BY COD_ANO_MES;    
                     
                    
             WHEN PCASEBUSQUEDA='TB'  THEN  
                SELECT SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN INTO  FILTERANUSD ,FILTERANPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  SUBSTR(COD_ANO_MES,0,4)  = SUBSTR(PBUSQUEDAINIF,0,4) AND  COD_BROKER = PBROKER
                    GROUP BY SUBSTR(COD_ANO_MES,0,4);                    
                SELECT        
                    SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN 
                    INTO  FILTERMONUSD  ,FILTERMONPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  COD_ANO_MES = PBUSQUEDAINIF AND  COD_BROKER = PBROKER
                    GROUP BY COD_ANO_MES; 
                    
             WHEN PCASEBUSQUEDA='TGB'  THEN  
                SELECT SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN INTO  FILTERANUSD ,FILTERANPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  SUBSTR(COD_ANO_MES,0,4)  = SUBSTR(PBUSQUEDAINIF,0,4)  AND COD_REGION = PREGION   AND COD_BROKER = PBROKER
                    GROUP BY SUBSTR(COD_ANO_MES,0,4);                    
                SELECT        
                    SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN 
                    INTO  FILTERMONUSD  ,FILTERMONPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  COD_ANO_MES = PBUSQUEDAINIF AND  COD_REGION = PREGION   AND COD_BROKER = PBROKER
                    GROUP BY COD_ANO_MES; 
             WHEN PCASEBUSQUEDA='TCGB'  THEN  
                SELECT SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN INTO  FILTERANUSD ,FILTERANPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  COD_COMPANIA = PCOMPANIA  AND SUBSTR(COD_ANO_MES,0,4)  = SUBSTR(PBUSQUEDAINIF,0,4)  AND COD_REGION = PREGION   AND COD_BROKER = PBROKER
                    GROUP BY SUBSTR(COD_ANO_MES,0,4);                    
                SELECT        
                    SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN 
                    INTO  FILTERMONUSD  ,FILTERMONPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  COD_COMPANIA = PCOMPANIA AND COD_ANO_MES = PBUSQUEDAINIF AND  COD_REGION = PREGION   AND COD_BROKER = PBROKER
                    GROUP BY COD_ANO_MES;        
            WHEN PCASEBUSQUEDA='TCRGB'  THEN  
                SELECT SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN INTO  FILTERANUSD ,FILTERANPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  SUBSTR(COD_ANO_MES,0,4)  = SUBSTR(PBUSQUEDAINIF,0,4)  AND COD_COMPANIA = PCOMPANIA AND 
                                COD_RAMO_COMERCIAL=PRAMO AND 
                                COD_REGION = PREGION   AND COD_BROKER = PBROKER
                    GROUP BY SUBSTR(COD_ANO_MES,0,4);                    
                SELECT        
                    SUM(MONTO_USD)MONTO_USD ,SUM(MONTO_PEN) MONTO_PEN 
                    INTO  FILTERMONUSD  ,FILTERMONPEN                    
                    FROM WEBCORREDORES.NETO_COASEGURO 
                    WHERE  COD_ANO_MES = PBUSQUEDAINIF AND  COD_REGION = PREGION   AND COD_COMPANIA = PCOMPANIA AND 
                                COD_RAMO_COMERCIAL=PRAMO AND 
                                COD_REGION = PREGION   AND COD_BROKER = PBROKER
                    GROUP BY COD_ANO_MES; 
            END CASE;         
            EXCEPTION
                  WHEN no_data_found
                  THEN
                    FILTERMONUSD := 0; FILTERMONPEN := 0; FILTERANUSD := 0; FILTERANPEN := 0;            
            END;  
    END CORREDORES_AVANCE_PRD;

END "CORREDORES_PKG_PRODUCCION";
/