CREATE OR REPLACE PACKAGE WEBCORREDORES."CORREDORES_PKG_POTENCIAL"
AS
     PROCEDURE CORREDORES_GET_COMISION( 
      PCOMPANIA IN WEBCORREDORES.COMISION.COD_COMPANIA%TYPE,
      PRAMO IN WEBCORREDORES.COMISION.COD_RAMO_COMERCIAL%TYPE,
      PBROKER IN WEBCORREDORES.COMISION.COD_BROKER%TYPE, 
      PBUSQUEDAINI IN VARCHAR2,    
      FECHA_ACTUALIZACION OUT VARCHAR2,  
      POCURSORD0 OUT SYS_REFCURSOR,  
      POCURSORD3 OUT SYS_REFCURSOR,  
      POCURSORD6 OUT SYS_REFCURSOR,  
      POCURSORD9 OUT SYS_REFCURSOR); 
    
     PROCEDURE CORREDORES_GET_CLIENTES_TOP( 
      PCOMPANIA IN WEBCORREDORES.COMISION.COD_COMPANIA%TYPE,
      PRAMO IN WEBCORREDORES.COMISION.COD_RAMO_COMERCIAL%TYPE,
      PBROKER IN WEBCORREDORES.COMISION.COD_BROKER%TYPE, 
      PBUSQUEDAINI IN VARCHAR2,    
      CANTIDAD_REGISTROS IN VARCHAR2,    
      DIAS_BUSQUEDA IN VARCHAR2,    
      FECHA_ACTUALIZACION OUT VARCHAR2,  
      POCURSOR OUT SYS_REFCURSOR); 
      
     PROCEDURE CORREDORES_GET_PRD_RIESGO( 
      PCOMPANIA IN WEBCORREDORES.COMISION.COD_COMPANIA%TYPE,
      PRAMO IN WEBCORREDORES.COMISION.COD_RAMO_COMERCIAL%TYPE,
      PBROKER IN WEBCORREDORES.COMISION.COD_BROKER%TYPE, 
      PBUSQUEDAINI IN VARCHAR2,    
      FILTROS_BUSQUEDA IN VARCHAR2,   
      FILTROS_PERIODO IN VARCHAR2, 
      FECHA_ACTUALIZACION OUT VARCHAR2,     
      POCURSOR OUT SYS_REFCURSOR);
      
      PROCEDURE CORREDORES_GET_PRD_RIESGO_DET( 
      PCOMPANIA IN WEBCORREDORES.COMISION.COD_COMPANIA%TYPE,
      PRAMO IN WEBCORREDORES.COMISION.COD_RAMO_COMERCIAL%TYPE,
      PBROKER IN WEBCORREDORES.COMISION.COD_BROKER%TYPE, 
      PBUSQUEDAINI IN VARCHAR2,   
      FILTROS_BUSQUEDA IN VARCHAR2,   
      FILTROS_PERIODO IN VARCHAR2,
      FECHA_ACTUALIZACION OUT VARCHAR2,   
      NOM_BROKER OUT VARCHAR2,   
      NOM_COMPANIA OUT VARCHAR2,   
      NOM_RAMO_COMERCIAL OUT VARCHAR2,      
      POCURSOR OUT SYS_REFCURSOR,      
      PRAMOCURSOR OUT SYS_REFCURSOR,      
      PCOMPANIACURSOR OUT SYS_REFCURSOR,      
      PBROKERCURSOR OUT SYS_REFCURSOR);
      FUNCTION GENERAR_CONSULTA
        ( FILTROS_BUSQUEDA IN varchar2, FILTRO_WHEN IN varchar2 , FILTROS_PERIODO IN VARCHAR2,
      GRUPO_BUSQUEDA IN VARCHAR2, PARAMETROS VARCHAR2)
        RETURN VARCHAR2;
END "CORREDORES_PKG_POTENCIAL";
/


CREATE OR REPLACE PACKAGE BODY WEBCORREDORES."CORREDORES_PKG_POTENCIAL"
AS
    PROCEDURE CORREDORES_GET_COMISION( 
      PCOMPANIA IN WEBCORREDORES.COMISION.COD_COMPANIA%TYPE,
      PRAMO IN WEBCORREDORES.COMISION.COD_RAMO_COMERCIAL%TYPE,
      PBROKER IN WEBCORREDORES.COMISION.COD_BROKER%TYPE, 
      PBUSQUEDAINI IN VARCHAR2,  
      FECHA_ACTUALIZACION OUT VARCHAR2,  
      POCURSORD0 OUT SYS_REFCURSOR,  
      POCURSORD3 OUT SYS_REFCURSOR,  
      POCURSORD6 OUT SYS_REFCURSOR,  
      POCURSORD9 OUT SYS_REFCURSOR
      )
        AS
        BEGIN
            SELECT FEC_ACTUALIZACION INTO FECHA_ACTUALIZACION FROM WEBCORREDORES.COMISION WHERE ROWNUM =1 ;
            
            CASE
            WHEN PBUSQUEDAINI = 'T' THEN
                OPEN POCURSORD0 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL, SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) = 0 AND ESTADO_COMISION = 'P';                     
                OPEN POCURSORD3 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL , SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 30 AND 
                        ESTADO_COMISION = 'P';   
                OPEN POCURSORD6 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL  , SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION 
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 60 AND ESTADO_COMISION = 'P';
                OPEN POCURSORD9 FOR 
                    SELECT   SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL, SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 90 AND ESTADO_COMISION = 'P' ;  
            
            WHEN PBUSQUEDAINI = 'TC' THEN
            OPEN POCURSORD0 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL, SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) = 0 AND ESTADO_COMISION = 'P' AND COD_COMPANIA = PCOMPANIA;                     
                OPEN POCURSORD3 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL , SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 30 AND 
                        ESTADO_COMISION = 'P' AND COD_COMPANIA = PCOMPANIA;    
                OPEN POCURSORD6 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL  , SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION 
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 60 AND ESTADO_COMISION = 'P' AND COD_COMPANIA = PCOMPANIA; 
                OPEN POCURSORD9 FOR 
                    SELECT   SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL, SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 90 AND ESTADO_COMISION = 'P' AND COD_COMPANIA = PCOMPANIA;  
            WHEN PBUSQUEDAINI = 'TR' THEN
            OPEN POCURSORD0 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL, SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) = 0 AND ESTADO_COMISION = 'P' AND COD_RAMO_COMERCIAL = PRAMO;                      
                OPEN POCURSORD3 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL , SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 30 AND COD_RAMO_COMERCIAL = PRAMO AND 
                        ESTADO_COMISION = 'P';   
                OPEN POCURSORD6 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL , SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD 
                    FROM WEBCORREDORES.COMISION 
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 60 AND COD_RAMO_COMERCIAL = PRAMO AND ESTADO_COMISION = 'P';
                OPEN POCURSORD9 FOR 
                    SELECT   SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL, SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 90 AND COD_RAMO_COMERCIAL = PRAMO AND ESTADO_COMISION = 'P' ;  
            WHEN PBUSQUEDAINI = 'TB' THEN
            OPEN POCURSORD0 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL, SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) = 0 AND ESTADO_COMISION = 'P' AND COD_BROKER = PBROKER;                     
                OPEN POCURSORD3 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL , SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) >= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 30 AND COD_BROKER = PBROKER AND 
                        ESTADO_COMISION = 'P';   
                OPEN POCURSORD6 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL  , SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION 
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 60 AND COD_BROKER = PBROKER AND ESTADO_COMISION = 'P';
                OPEN POCURSORD9 FOR 
                    SELECT   SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL, SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 90 AND COD_BROKER = PBROKER AND ESTADO_COMISION = 'P' ;  
            WHEN PBUSQUEDAINI = 'TCR' THEN
            OPEN POCURSORD0 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL, SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) = 0 AND ESTADO_COMISION = 'P' AND COD_COMPANIA = PCOMPANIA AND COD_RAMO_COMERCIAL = PRAMO;                     
                OPEN POCURSORD3 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL , SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 30 AND COD_COMPANIA = PCOMPANIA AND COD_RAMO_COMERCIAL = PRAMO AND 
                        ESTADO_COMISION = 'P';   
                OPEN POCURSORD6 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL  , SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION 
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 60 AND COD_COMPANIA = PCOMPANIA AND COD_RAMO_COMERCIAL = PRAMO AND ESTADO_COMISION = 'P';
                OPEN POCURSORD9 FOR 
                    SELECT   SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL, SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 90 AND COD_COMPANIA = PCOMPANIA AND COD_RAMO_COMERCIAL = PRAMO AND ESTADO_COMISION = 'P' ;  
            WHEN PBUSQUEDAINI = 'TCB' THEN
            OPEN POCURSORD0 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL, SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) = 0 AND ESTADO_COMISION = 'P' AND COD_COMPANIA = PCOMPANIA AND COD_BROKER = PBROKER;                     
                OPEN POCURSORD3 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL , SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 30 AND COD_COMPANIA = PCOMPANIA AND COD_BROKER = PBROKER AND 
                        ESTADO_COMISION = 'P';   
                OPEN POCURSORD6 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL  , SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION 
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 60 AND COD_COMPANIA = PCOMPANIA AND COD_BROKER = PBROKER AND ESTADO_COMISION = 'P';
                OPEN POCURSORD9 FOR 
                    SELECT   SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL, SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 90 AND COD_COMPANIA = PCOMPANIA AND COD_BROKER = PBROKER AND ESTADO_COMISION = 'P' ;  
            WHEN PBUSQUEDAINI = 'TCRB' THEN
            OPEN POCURSORD0 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL, SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) = 0 AND ESTADO_COMISION = 'P' AND COD_COMPANIA = PCOMPANIA AND COD_BROKER = PBROKER AND COD_RAMO_COMERCIAL = PRAMO;                     
                OPEN POCURSORD3 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL , SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 30 AND COD_COMPANIA = PCOMPANIA AND COD_BROKER = PBROKER AND COD_RAMO_COMERCIAL = PRAMO AND 
                        ESTADO_COMISION = 'P';   
                OPEN POCURSORD6 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL  , SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION 
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 60 AND COD_COMPANIA = PCOMPANIA AND COD_BROKER = PBROKER AND COD_RAMO_COMERCIAL = PRAMO AND ESTADO_COMISION = 'P';
                OPEN POCURSORD9 FOR 
                    SELECT   SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL, SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 90 AND COD_COMPANIA = PCOMPANIA AND COD_BROKER = PBROKER AND COD_RAMO_COMERCIAL = PRAMO AND ESTADO_COMISION = 'P' ;  
            WHEN PBUSQUEDAINI = 'TRB' THEN
            OPEN POCURSORD0 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL, SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) = 0 AND ESTADO_COMISION = 'P'  AND COD_BROKER = PBROKER AND COD_RAMO_COMERCIAL = PRAMO;                     
                OPEN POCURSORD3 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL , SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 30 AND COD_BROKER = PBROKER AND COD_RAMO_COMERCIAL = PRAMO AND 
                        ESTADO_COMISION = 'P';   
                OPEN POCURSORD6 FOR 
                    SELECT SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL  , SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION 
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 60 AND COD_BROKER = PBROKER AND COD_RAMO_COMERCIAL = PRAMO AND ESTADO_COMISION = 'P';
                OPEN POCURSORD9 FOR 
                    SELECT   SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL, SUM(COMISION_USD)  COMISION_POTENCIAL_USD,  SUM(PRIMA_DOL) PRIMA_EMITIDA_USD
                    FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND)>= 0 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= 90 AND COD_BROKER = PBROKER AND COD_RAMO_COMERCIAL = PRAMO AND ESTADO_COMISION = 'P' ;  
 
            END CASE;

    END CORREDORES_GET_COMISION;
    
    PROCEDURE CORREDORES_GET_CLIENTES_TOP( 
      PCOMPANIA IN WEBCORREDORES.COMISION.COD_COMPANIA%TYPE,
      PRAMO IN WEBCORREDORES.COMISION.COD_RAMO_COMERCIAL%TYPE,
      PBROKER IN WEBCORREDORES.COMISION.COD_BROKER%TYPE, 
      PBUSQUEDAINI IN VARCHAR2,    
      CANTIDAD_REGISTROS IN VARCHAR2, 
      DIAS_BUSQUEDA IN VARCHAR2,    
      FECHA_ACTUALIZACION OUT VARCHAR2,  
      POCURSOR OUT SYS_REFCURSOR)
      AS
        BEGIN   
            
         SELECT FEC_ACTUALIZACION INTO FECHA_ACTUALIZACION FROM WEBCORREDORES.COMISION WHERE ROWNUM =1 ;
         CASE
            WHEN PBUSQUEDAINI = 'T' THEN
                OPEN POCURSOR FOR 
                    SELECT COD_CLIENTE,NOMBRE_CLIENTE , PRIMA_EMITIDA, COMISION_POTENCIAL , PRIMA_EMITIDA_DOL,  COMISION_POTENCIAL_DOL , CANTIDAD_POLIZAS , CANTIDAD_DOC_COBRO  FROM( SELECT COD_CLIENTE,NOMBRE_CLIENTE , SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL ,
                        SUM(PRIMA_DOL) PRIMA_EMITIDA_DOL,SUM(COMISION_USD)  COMISION_POTENCIAL_DOL , SUM(CANTIDAD_POLIZAS) CANTIDAD_POLIZAS,  SUM(CANTIDAD_DOC_COBRO) CANTIDAD_DOC_COBRO 
                            FROM WEBCORREDORES.COMISION
                        WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) > -1 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= DIAS_BUSQUEDA   AND ESTADO_COMISION = 'P'
                        GROUP BY COD_CLIENTE, NOMBRE_CLIENTE)
                        WHERE ROWNUM <= CANTIDAD_REGISTROS;
            WHEN PBUSQUEDAINI = 'TC' THEN
                OPEN POCURSOR FOR 
                    SELECT COD_CLIENTE,NOMBRE_CLIENTE , PRIMA_EMITIDA, COMISION_POTENCIAL , PRIMA_EMITIDA_DOL,  COMISION_POTENCIAL_DOL , CANTIDAD_POLIZAS , CANTIDAD_DOC_COBRO  FROM( SELECT COD_CLIENTE,NOMBRE_CLIENTE , SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL ,
                        SUM(PRIMA_DOL) PRIMA_EMITIDA_DOL,SUM(COMISION_USD)  COMISION_POTENCIAL_DOL , SUM(CANTIDAD_POLIZAS) CANTIDAD_POLIZAS,  SUM(CANTIDAD_DOC_COBRO) CANTIDAD_DOC_COBRO 
                            FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) > -1 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= DIAS_BUSQUEDA AND ESTADO_COMISION = 'P'
                     AND COD_COMPANIA = PCOMPANIA
                   GROUP BY COD_CLIENTE, NOMBRE_CLIENTE)
                        WHERE ROWNUM <= CANTIDAD_REGISTROS;  
            WHEN PBUSQUEDAINI = 'TR' THEN
                OPEN POCURSOR FOR 
                    SELECT COD_CLIENTE,NOMBRE_CLIENTE , PRIMA_EMITIDA, COMISION_POTENCIAL , PRIMA_EMITIDA_DOL,  COMISION_POTENCIAL_DOL , CANTIDAD_POLIZAS , CANTIDAD_DOC_COBRO  FROM( SELECT COD_CLIENTE,NOMBRE_CLIENTE , SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL ,
                        SUM(PRIMA_DOL) PRIMA_EMITIDA_DOL,SUM(COMISION_USD)  COMISION_POTENCIAL_DOL , SUM(CANTIDAD_POLIZAS) CANTIDAD_POLIZAS,  SUM(CANTIDAD_DOC_COBRO) CANTIDAD_DOC_COBRO 
                            FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) > -1 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= DIAS_BUSQUEDA AND ESTADO_COMISION = 'P'
                    AND ROWNUM <= CANTIDAD_REGISTROS AND COD_RAMO_COMERCIAL = PRAMO
                    GROUP BY COD_CLIENTE, NOMBRE_CLIENTE)
                        WHERE ROWNUM <= CANTIDAD_REGISTROS;
            WHEN PBUSQUEDAINI = 'TB' THEN
                OPEN POCURSOR FOR 
                    SELECT COD_CLIENTE,NOMBRE_CLIENTE , PRIMA_EMITIDA, COMISION_POTENCIAL , PRIMA_EMITIDA_DOL,  COMISION_POTENCIAL_DOL , CANTIDAD_POLIZAS , CANTIDAD_DOC_COBRO  FROM( SELECT COD_CLIENTE,NOMBRE_CLIENTE , SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL ,
                        SUM(PRIMA_DOL) PRIMA_EMITIDA_DOL,SUM(COMISION_USD)  COMISION_POTENCIAL_DOL , SUM(CANTIDAD_POLIZAS) CANTIDAD_POLIZAS,  SUM(CANTIDAD_DOC_COBRO) CANTIDAD_DOC_COBRO 
                            FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) > -1 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= DIAS_BUSQUEDA AND ESTADO_COMISION = 'P'
                      AND COD_BROKER = PBROKER
                   GROUP BY COD_CLIENTE, NOMBRE_CLIENTE)
                        WHERE ROWNUM <= CANTIDAD_REGISTROS;
            WHEN PBUSQUEDAINI = 'TCR' THEN
                OPEN POCURSOR FOR 
                    SELECT COD_CLIENTE,NOMBRE_CLIENTE , PRIMA_EMITIDA, COMISION_POTENCIAL , PRIMA_EMITIDA_DOL,  COMISION_POTENCIAL_DOL , CANTIDAD_POLIZAS , CANTIDAD_DOC_COBRO   FROM( SELECT COD_CLIENTE,NOMBRE_CLIENTE , SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL ,
                        SUM(PRIMA_DOL) PRIMA_EMITIDA_DOL,SUM(COMISION_USD)  COMISION_POTENCIAL_DOL , SUM(CANTIDAD_POLIZAS) CANTIDAD_POLIZAS,  SUM(CANTIDAD_DOC_COBRO) CANTIDAD_DOC_COBRO 
                            FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) > -1 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= DIAS_BUSQUEDA AND ESTADO_COMISION = 'P'
                     AND COD_COMPANIA = PCOMPANIA AND COD_RAMO_COMERCIAL = PRAMO
                    GROUP BY COD_CLIENTE, NOMBRE_CLIENTE)
                        WHERE ROWNUM <= CANTIDAD_REGISTROS;
            WHEN PBUSQUEDAINI = 'TCB' THEN
                OPEN POCURSOR FOR 
                    SELECT COD_CLIENTE,NOMBRE_CLIENTE , PRIMA_EMITIDA, COMISION_POTENCIAL , PRIMA_EMITIDA_DOL,  COMISION_POTENCIAL_DOL , CANTIDAD_POLIZAS , CANTIDAD_DOC_COBRO  FROM( SELECT COD_CLIENTE,NOMBRE_CLIENTE , SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL ,
                        SUM(PRIMA_DOL) PRIMA_EMITIDA_DOL,SUM(COMISION_USD)  COMISION_POTENCIAL_DOL , SUM(CANTIDAD_POLIZAS) CANTIDAD_POLIZAS,  SUM(CANTIDAD_DOC_COBRO) CANTIDAD_DOC_COBRO 
                            FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) > -1 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= DIAS_BUSQUEDA AND ESTADO_COMISION = 'P'
                     AND COD_COMPANIA = PCOMPANIA AND COD_BROKER = PBROKER
                   GROUP BY COD_CLIENTE, NOMBRE_CLIENTE)
                        WHERE ROWNUM <= CANTIDAD_REGISTROS;  
            WHEN PBUSQUEDAINI = 'TCRB' THEN
                OPEN POCURSOR FOR 
                    SELECT COD_CLIENTE,NOMBRE_CLIENTE , PRIMA_EMITIDA, COMISION_POTENCIAL , PRIMA_EMITIDA_DOL,  COMISION_POTENCIAL_DOL , CANTIDAD_POLIZAS , CANTIDAD_DOC_COBRO  FROM( SELECT COD_CLIENTE,NOMBRE_CLIENTE , SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL ,
                        SUM(PRIMA_DOL) PRIMA_EMITIDA_DOL,SUM(COMISION_USD)  COMISION_POTENCIAL_DOL , SUM(CANTIDAD_POLIZAS) CANTIDAD_POLIZAS,  SUM(CANTIDAD_DOC_COBRO) CANTIDAD_DOC_COBRO 
                            FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) > -1 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= DIAS_BUSQUEDA AND ESTADO_COMISION = 'P'
                     AND COD_COMPANIA = PCOMPANIA AND COD_BROKER = PBROKER AND COD_RAMO_COMERCIAL = PRAMO
                    GROUP BY COD_CLIENTE, NOMBRE_CLIENTE)
                        WHERE ROWNUM <= CANTIDAD_REGISTROS;
            WHEN PBUSQUEDAINI = 'TRB' THEN
                OPEN POCURSOR FOR 
                    SELECT COD_CLIENTE,NOMBRE_CLIENTE , PRIMA_EMITIDA, COMISION_POTENCIAL , PRIMA_EMITIDA_DOL,  COMISION_POTENCIAL_DOL , CANTIDAD_POLIZAS , CANTIDAD_DOC_COBRO
                      FROM( SELECT COD_CLIENTE,NOMBRE_CLIENTE , SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL ,
                        SUM(PRIMA_DOL) PRIMA_EMITIDA_DOL,SUM(COMISION_USD)  COMISION_POTENCIAL_DOL , SUM(CANTIDAD_POLIZAS) CANTIDAD_POLIZAS,  SUM(CANTIDAD_DOC_COBRO) CANTIDAD_DOC_COBRO 
                            FROM WEBCORREDORES.COMISION
                    WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) > -1 AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_PEND) <= DIAS_BUSQUEDA AND ESTADO_COMISION = 'P'
                     AND COD_BROKER = PBROKER AND COD_RAMO_COMERCIAL = PRAMO
                   GROUP BY COD_CLIENTE, NOMBRE_CLIENTE)
                        WHERE ROWNUM <= CANTIDAD_REGISTROS;
        END CASE;
        END CORREDORES_GET_CLIENTES_TOP;

    PROCEDURE CORREDORES_GET_PRD_RIESGO( 
      PCOMPANIA IN WEBCORREDORES.COMISION.COD_COMPANIA%TYPE,
      PRAMO IN WEBCORREDORES.COMISION.COD_RAMO_COMERCIAL%TYPE,
      PBROKER IN WEBCORREDORES.COMISION.COD_BROKER%TYPE, 
      PBUSQUEDAINI IN VARCHAR2,   
      FILTROS_BUSQUEDA IN VARCHAR2,   
      FILTROS_PERIODO IN VARCHAR2,
      FECHA_ACTUALIZACION OUT VARCHAR2,      
      POCURSOR OUT SYS_REFCURSOR)
      AS 
        INDEXOPCIONESBUSQUEDA BINARY_INTEGER;
        INDEX_BUSQUEDA   BINARY_INTEGER; 
        PARAMETRO_BUSQUEDA VARCHAR2(1000);
        COMANDO VARCHAR2(32000):=' ';  
      BEGIN
            INDEXOPCIONESBUSQUEDA := 0; 
            SELECT FEC_ACTUALIZACION INTO FECHA_ACTUALIZACION FROM WEBCORREDORES.COMISION WHERE ROWNUM =1 ;
            INDEX_BUSQUEDA   := INSTR(FILTROS_BUSQUEDA, ','); 
            CASE 
                WHEN PBUSQUEDAINI = 'T' THEN 
                COMANDO := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,'' , '' );
                WHEN PBUSQUEDAINI = 'TC' THEN 
                COMANDO := GENERAR_CONSULTA(FILTROS_BUSQUEDA, ' AND COD_COMPANIA =' ||  PCOMPANIA ,FILTROS_PERIODO,'' , '' );
                WHEN PBUSQUEDAINI = 'TR' THEN 
                COMANDO := GENERAR_CONSULTA(FILTROS_BUSQUEDA, ' AND COD_RAMO_COMERCIAL =' ||  PRAMO ,FILTROS_PERIODO,'' , '' );
                WHEN PBUSQUEDAINI = 'TB' THEN 
                COMANDO := GENERAR_CONSULTA(FILTROS_BUSQUEDA, ' AND COD_BROKER =' ||  PBROKER ,FILTROS_PERIODO,'' , '' );
                WHEN PBUSQUEDAINI = 'TCR' THEN 
                COMANDO := GENERAR_CONSULTA(FILTROS_BUSQUEDA, ' AND COD_RAMO_COMERCIAL =' ||  PRAMO || ' AND COD_COMPANIA =' ||  PCOMPANIA  ,FILTROS_PERIODO,'' , '' );
                WHEN PBUSQUEDAINI = 'TCB' THEN 
                COMANDO := GENERAR_CONSULTA(FILTROS_BUSQUEDA, ' AND COD_BROKER =' ||  PBROKER || ' AND COD_COMPANIA =' ||  PCOMPANIA  ,FILTROS_PERIODO,'' , '' );
                WHEN PBUSQUEDAINI = 'TCRB' THEN 
                COMANDO := GENERAR_CONSULTA(FILTROS_BUSQUEDA, ' AND COD_BROKER =' ||  PBROKER || ' AND COD_RAMO_COMERCIAL =' ||  PRAMO || ' AND COD_COMPANIA =' ||  PCOMPANIA  ,FILTROS_PERIODO,'' , '' );
                WHEN PBUSQUEDAINI = 'TRB' THEN 
                COMANDO := GENERAR_CONSULTA(FILTROS_BUSQUEDA, ' AND COD_BROKER =' ||  PBROKER || ' AND COD_RAMO_COMERCIAL =' ||  PRAMO  ,FILTROS_PERIODO,'' , '' );
 
            END CASE;
                   

       OPEN POCURSOR FOR COMANDO;
       END CORREDORES_GET_PRD_RIESGO;    
       
       
  FUNCTION GENERAR_CONSULTA
   ( FILTROS_BUSQUEDA IN varchar2 , FILTRO_WHEN IN varchar2  ,FILTROS_PERIODO IN VARCHAR2, 
      GRUPO_BUSQUEDA IN VARCHAR2, PARAMETROS IN VARCHAR2)
   RETURN VARCHAR2
IS
    INDEXOPCIONESBUSQUEDA BINARY_INTEGER;
    INDEX_BUSQUEDA   BINARY_INTEGER; 
    FILTROS_BUSQUEDA_TEMP VARCHAR2(100);
    FILTRO_BUSQUEDA_CON VARCHAR2(100);
    PARAMETRO_BUSQUEDA VARCHAR2(1000);
    COMANDO VARCHAR2(32000):=' ';  
    ACUMULADO VARCHAR(5):='-1';  
BEGIN
    FILTROS_BUSQUEDA_TEMP := FILTROS_BUSQUEDA;
    IF  FILTROS_PERIODO <> 'P' THEN 
        ACUMULADO := SUBSTR(FILTROS_BUSQUEDA_TEMP,0,INSTR(FILTROS_BUSQUEDA_TEMP,',')-1); 
        FILTROS_BUSQUEDA_TEMP := SUBSTR(FILTROS_BUSQUEDA_TEMP,length(ACUMULADO) + 2) ; 
    END IF;   
    INDEXOPCIONESBUSQUEDA := 0;  
    INDEX_BUSQUEDA   := INSTR(FILTROS_BUSQUEDA_TEMP, ','); 
   WHILE(INDEX_BUSQUEDA > 0) LOOP  
             
       PARAMETRO_BUSQUEDA := SUBSTR(FILTROS_BUSQUEDA_TEMP, INDEXOPCIONESBUSQUEDA+1, INDEX_BUSQUEDA - INDEXOPCIONESBUSQUEDA - 1);  
        IF  FILTROS_PERIODO <> 'P' THEN 
           FILTRO_BUSQUEDA_CON := TO_CHAR(ACUMULADO||'-'||PARAMETRO_BUSQUEDA);  
        ELSE 
            FILTRO_BUSQUEDA_CON := PARAMETRO_BUSQUEDA;
        END IF;  
        IF ACUMULADO = '0' THEN 
         COMANDO := COMANDO || 'SELECT  '|| PARAMETROS ||' SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL , SUM(PRIMA_DOL) PRIMA_EMITIDA_USD,SUM(COMISION_USD)  COMISION_POTENCIAL_USD ,''' ||TO_CHAR(FILTRO_BUSQUEDA_CON)  ||''' AS PERIODO_BUSQUEDA  
         FROM WEBCORREDORES.COMISION WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_RIES) >= ' ||TO_NUMBER(ACUMULADO,99)||'  AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_RIES) <= ' || PARAMETRO_BUSQUEDA || FILTRO_WHEN ||' AND ESTADO_COMISION = ''R'' ' ||GRUPO_BUSQUEDA ||' UNION ALL ';
        ELSE 
         COMANDO := COMANDO || 'SELECT  '|| PARAMETROS ||'  SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL , SUM(PRIMA_DOL) PRIMA_EMITIDA_USD,SUM(COMISION_USD)  COMISION_POTENCIAL_USD ,''' ||TO_CHAR(FILTRO_BUSQUEDA_CON)  ||''' AS PERIODO_BUSQUEDA  
       FROM WEBCORREDORES.COMISION WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_RIES) > ' ||TO_NUMBER(ACUMULADO,99)||'  AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_RIES) <= ' || PARAMETRO_BUSQUEDA || FILTRO_WHEN ||' AND ESTADO_COMISION = ''R'' ' ||GRUPO_BUSQUEDA ||' UNION ALL ';

        END IF;
             INDEXOPCIONESBUSQUEDA := INDEX_BUSQUEDA;
       INDEX_BUSQUEDA := INSTR(FILTROS_BUSQUEDA_TEMP, ',', INDEXOPCIONESBUSQUEDA + 1); 
 
        IF  FILTROS_PERIODO <> 'P' THEN  
           ACUMULADO := PARAMETRO_BUSQUEDA; 
        END IF;  
      
   END LOOP; 
  PARAMETRO_BUSQUEDA := SUBSTR(FILTROS_BUSQUEDA_TEMP, INDEXOPCIONESBUSQUEDA+1);
   IF  FILTROS_PERIODO = 'P' THEN -- SOLO CUANDO ES POR PERIODOS 
    FILTRO_BUSQUEDA_CON := PARAMETRO_BUSQUEDA;
    IF ACUMULADO = '0' THEN 
        COMANDO := COMANDO || 'SELECT  '|| PARAMETROS ||'  SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL , SUM(PRIMA_DOL) PRIMA_EMITIDA_USD,SUM(COMISION_USD)  COMISION_POTENCIAL_USD ,'''||TO_CHAR(FILTRO_BUSQUEDA_CON)||''' AS PERIODO_BUSQUEDA  
        FROM WEBCORREDORES.COMISION WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_RIES) >= '||TO_NUMBER(ACUMULADO,99)||'  AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_RIES) =< ' || PARAMETRO_BUSQUEDA || FILTRO_WHEN ||' AND ESTADO_COMISION = ''R''  ' ||GRUPO_BUSQUEDA ||'   ORDER BY PERIODO_BUSQUEDA ASC'; 
    ELSE
        COMANDO := COMANDO || 'SELECT '|| PARAMETROS ||'   SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL , SUM(PRIMA_DOL) PRIMA_EMITIDA_USD,SUM(COMISION_USD)  COMISION_POTENCIAL_USD ,'''||TO_CHAR(FILTRO_BUSQUEDA_CON)||''' AS PERIODO_BUSQUEDA  
        FROM WEBCORREDORES.COMISION WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_RIES) > '||TO_NUMBER(ACUMULADO,99)||'  AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_RIES) <= ' || PARAMETRO_BUSQUEDA || FILTRO_WHEN ||' AND ESTADO_COMISION = ''R''  ' ||GRUPO_BUSQUEDA ||'   ORDER BY PERIODO_BUSQUEDA ASC'; 
    END IF;
  ELSE 
     FILTRO_BUSQUEDA_CON :=  TO_CHAR(ACUMULADO||'-'||PARAMETRO_BUSQUEDA); 
    COMANDO := COMANDO || ' SELECT  '|| PARAMETROS ||'   SUM(PRIMA_SOL) PRIMA_EMITIDA,SUM(COMISION_SOL)  COMISION_POTENCIAL , SUM(PRIMA_DOL) PRIMA_EMITIDA_USD,SUM(COMISION_USD)  COMISION_POTENCIAL_USD ,''' ||TO_CHAR(FILTRO_BUSQUEDA_CON)||''' AS PERIODO_BUSQUEDA  
   FROM WEBCORREDORES.COMISION WHERE TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_RIES) > '||TO_NUMBER(ACUMULADO,99)||'  AND TRUNC(SYSDATE) - TRUNC(VENCIMIENTO_COMI_RIES) <= ' || PARAMETRO_BUSQUEDA || FILTRO_WHEN ||' AND ESTADO_COMISION = ''R''  ' ||GRUPO_BUSQUEDA ||'   ORDER BY PERIODO_BUSQUEDA ASC'; 

  END IF;
   dbms_output.put_line('---- ' || COMANDO ||' ----');
RETURN COMANDO;    
END GENERAR_CONSULTA;    



 PROCEDURE CORREDORES_GET_PRD_RIESGO_DET( 
      PCOMPANIA IN WEBCORREDORES.COMISION.COD_COMPANIA%TYPE,
      PRAMO IN WEBCORREDORES.COMISION.COD_RAMO_COMERCIAL%TYPE,
      PBROKER IN WEBCORREDORES.COMISION.COD_BROKER%TYPE, 
      PBUSQUEDAINI IN VARCHAR2,   
      FILTROS_BUSQUEDA IN VARCHAR2,   
      FILTROS_PERIODO IN VARCHAR2,
      FECHA_ACTUALIZACION OUT VARCHAR2,   
      NOM_BROKER OUT VARCHAR2,   
      NOM_COMPANIA OUT VARCHAR2,   
      NOM_RAMO_COMERCIAL OUT VARCHAR2,      
      POCURSOR OUT SYS_REFCURSOR,      
      PRAMOCURSOR OUT SYS_REFCURSOR,      
      PCOMPANIACURSOR OUT SYS_REFCURSOR,      
      PBROKERCURSOR OUT SYS_REFCURSOR)
       AS 
        INDEXOPCIONESBUSQUEDA BINARY_INTEGER;
        INDEX_BUSQUEDA   BINARY_INTEGER; 
        PARAMETRO_BUSQUEDA VARCHAR2(1000);
        COMANDO VARCHAR2(32000):=' ';  
        COMANDO_REGION VARCHAR2(32000):=' ';  
        COMANDO_COMPANIA VARCHAR2(32000):=' ';  
        COMANDO_BROKER VARCHAR2(32000):=' ';  
      BEGIN
            INDEXOPCIONESBUSQUEDA := 0; 
             SELECT FEC_ACTUALIZACION INTO FECHA_ACTUALIZACION  
                FROM WEBCORREDORES.COMISION WHERE ROWNUM =1;
                
            BEGIN 
            SELECT NOM_BROKER INTO NOM_BROKER  
                FROM WEBCORREDORES.COMISION WHERE ROWNUM =1 AND COD_BROKER = PBROKER;
            EXCEPTION
                  WHEN no_data_found
                  THEN
                    NOM_BROKER := 'Todos'; 
            END;
            BEGIN 
            SELECT NOM_COMPANIA INTO NOM_COMPANIA  
                FROM WEBCORREDORES.COMISION WHERE ROWNUM =1 AND COD_COMPANIA = PCOMPANIA;
            EXCEPTION
                  WHEN no_data_found
                  THEN
                    NOM_COMPANIA := 'Todos'; 
            END;
            BEGIN 
            SELECT NOM_RAMO_COMERCIAL INTO NOM_RAMO_COMERCIAL  
                FROM WEBCORREDORES.COMISION WHERE ROWNUM =1 AND COD_RAMO_COMERCIAL = PRAMO;
            EXCEPTION
                  WHEN no_data_found
                  THEN
                    NOM_RAMO_COMERCIAL := 'Todos'; 
            END;
            
            
            
            INDEX_BUSQUEDA   := INSTR(FILTROS_BUSQUEDA, ','); 
            CASE 
                WHEN PBUSQUEDAINI = 'T' THEN 
                COMANDO := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,'' ,' 1 AS DESCRIPCION, ' );
                COMANDO_COMPANIA := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_COMPANIA, NOM_COMPANIA ' ,' COD_COMPANIA , NOM_COMPANIA AS DESCRIPCION , ' );
                COMANDO_REGION := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL',' COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL AS DESCRIPCION  , ');
                COMANDO_BROKER := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_BROKER, NOM_BROKER',' COD_BROKER, NOM_BROKER AS DESCRIPCION  , ');
                WHEN PBUSQUEDAINI = 'TC' THEN 
                COMANDO := GENERAR_CONSULTA(FILTROS_BUSQUEDA, ' AND COD_COMPANIA =' ||  PCOMPANIA ,FILTROS_PERIODO,'',' 1 AS DESCRIPCION, ');
                COMANDO_COMPANIA := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_COMPANIA, NOM_COMPANIA ' ,' COD_COMPANIA , NOM_COMPANIA AS DESCRIPCION , ' );
                COMANDO_REGION := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL',' COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL  AS DESCRIPCION , ');
                COMANDO_BROKER := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_BROKER, NOM_BROKER',' COD_BROKER, NOM_BROKER AS DESCRIPCION , ');
                WHEN PBUSQUEDAINI = 'TR' THEN 
                COMANDO := GENERAR_CONSULTA(FILTROS_BUSQUEDA, ' AND COD_RAMO_COMERCIAL =' ||  PRAMO ,FILTROS_PERIODO,'' ,' 1 AS DESCRIPCION, ');
                COMANDO_COMPANIA := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_COMPANIA, NOM_COMPANIA ' ,' COD_COMPANIA , NOM_COMPANIA AS DESCRIPCION , ' );
                COMANDO_REGION := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL',' COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL AS DESCRIPCION , ');
                COMANDO_BROKER := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_BROKER, NOM_BROKER',' COD_BROKER, NOM_BROKER AS DESCRIPCION , ');
                WHEN PBUSQUEDAINI = 'TB' THEN 
                COMANDO := GENERAR_CONSULTA(FILTROS_BUSQUEDA, ' AND COD_BROKER =' ||  PBROKER ,FILTROS_PERIODO,'' ,' 1 AS DESCRIPCION, ');
                COMANDO_COMPANIA := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_COMPANIA, NOM_COMPANIA ' ,' COD_COMPANIA , NOM_COMPANIA AS DESCRIPCION , ' );
                COMANDO_REGION := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL',' COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL AS DESCRIPCION , ');
                COMANDO_BROKER := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_BROKER, NOM_BROKER',' COD_BROKER, NOM_BROKER AS DESCRIPCION , ');
                WHEN PBUSQUEDAINI = 'TCR' THEN 
                COMANDO := GENERAR_CONSULTA(FILTROS_BUSQUEDA, ' AND COD_RAMO_COMERCIAL =' ||  PRAMO || ' AND COD_COMPANIA =' ||  PCOMPANIA  ,FILTROS_PERIODO,'' ,' 1 AS DESCRIPCION, ');
               COMANDO_COMPANIA := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_COMPANIA, NOM_COMPANIA ' ,' COD_COMPANIA , NOM_COMPANIA AS DESCRIPCION , ' );
                COMANDO_REGION := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL',' COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL AS DESCRIPCION , ');
                COMANDO_BROKER := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_BROKER, NOM_BROKER',' COD_BROKER, NOM_BROKER AS DESCRIPCION , ');
                WHEN PBUSQUEDAINI = 'TCB' THEN 
                COMANDO := GENERAR_CONSULTA(FILTROS_BUSQUEDA, ' AND COD_BROKER =' ||  PBROKER || ' AND COD_COMPANIA =' ||  PCOMPANIA  ,FILTROS_PERIODO,'' ,' 1 AS DESCRIPCION, ');
                COMANDO_COMPANIA := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_COMPANIA, NOM_COMPANIA ' ,' COD_COMPANIA , NOM_COMPANIA AS DESCRIPCION , ' );
                COMANDO_REGION := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL',' COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL AS DESCRIPCION , ');
                COMANDO_BROKER := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_BROKER, NOM_BROKER',' COD_BROKER, NOM_BROKER AS DESCRIPCION , ');
                WHEN PBUSQUEDAINI = 'TCRB' THEN 
                COMANDO := GENERAR_CONSULTA(FILTROS_BUSQUEDA, ' AND COD_BROKER =' ||  PBROKER || ' AND COD_RAMO_COMERCIAL =' ||  PRAMO || ' AND COD_COMPANIA =' ||  PCOMPANIA  ,FILTROS_PERIODO,'' ,' 1 AS DESCRIPCION, ');
                COMANDO_COMPANIA := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_COMPANIA, NOM_COMPANIA ' ,' COD_COMPANIA , NOM_COMPANIA  AS DESCRIPCION , ' );
                COMANDO_REGION := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL',' COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL AS DESCRIPCION  , ');
                COMANDO_BROKER := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_BROKER, NOM_BROKER',' COD_BROKER, NOM_BROKER AS DESCRIPCION , ');
                WHEN PBUSQUEDAINI = 'TRB' THEN 
                COMANDO := GENERAR_CONSULTA(FILTROS_BUSQUEDA, ' AND COD_BROKER =' ||  PBROKER || ' AND COD_RAMO_COMERCIAL =' ||  PRAMO  ,FILTROS_PERIODO,'' ,' 1 AS DESCRIPCION, ');
                COMANDO_COMPANIA := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_COMPANIA, NOM_COMPANIA ' ,' COD_COMPANIA , NOM_COMPANIA AS DESCRIPCION , ' );
                COMANDO_REGION := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL',' COD_RAMO_COMERCIAL, NOM_RAMO_COMERCIAL AS DESCRIPCION , ');
                COMANDO_BROKER := GENERAR_CONSULTA(FILTROS_BUSQUEDA, '' ,FILTROS_PERIODO,' GROUP BY COD_BROKER, NOM_BROKER',' COD_BROKER, NOM_BROKER AS DESCRIPCION , ');
 
            END CASE;
                   

       OPEN POCURSOR FOR COMANDO;
       OPEN PRAMOCURSOR FOR COMANDO_REGION;
       OPEN PCOMPANIACURSOR FOR COMANDO_COMPANIA ;
       OPEN PBROKERCURSOR FOR COMANDO_BROKER; 
END CORREDORES_GET_PRD_RIESGO_DET;    
END "CORREDORES_PKG_POTENCIAL";
/